// Hand-written records: the Poles-03 bearing story, today's open work, requests, RCAs and warranty claims.
import type { Rca, WarrantyClaim } from '../../packages/types/src/index.ts'
import { fromWib, toIso } from '../../packages/fixtures/src/dates.ts'
import { A } from './assets.ts'
import type { MrSpec, Task, WoSpec } from './build.ts'
import { fcId } from './master.ts'

const t = (date: string, time: string) => {
  const [y, mo, d] = date.split('-').map(Number)
  const [h, m] = time.split(':').map(Number)
  return fromWib(y!, mo! - 1, d!, h!, m!)
}

const BEARING_PARTS = [
  { code: 'BRG-6204', qty: 2, status: 'consumed' as const },
  { code: 'SEL-ABC', qty: 1, status: 'consumed' as const },
]
const bearingValues = (runTest: number) => ({ 3: 'pass', 5: 50, 6: runTest })

// ─── Poles-03 repeat failure (17 Aug, 02 Sep, 20 Sep) ───────────

export const scriptedHistory: WoSpec[] = [
  {
    key: 'pol03-b1',
    asset: 'POL-03',
    title: 'Loud bearing noise, vibration 7.4 mm/s',
    description: 'Weekly motor inspection failed on vibration and noise. Replace drive bearings today.',
    type: 'corrective',
    priority: 'P2',
    status: 'closed',
    request: 'mr-pol03-insp-0817',
    plan: 'JP-POL-003',
    team: 'team-bdg-mech',
    assignees: ['per-budi', 'per-agus'],
    requestedBy: 'per-hendra',
    requestedAt: t('2026-08-17', '15:05'),
    assignedAt: t('2026-08-17', '15:10'),
    assignedBy: 'per-hendra',
    startedAt: t('2026-08-17', '15:30'),
    completedAt: t('2026-08-17', '18:20'),
    verified: { by: 'per-hendra', at: t('2026-08-18', '08:15'), note: 'Run test 1.9 mm/s.' },
    closed: { by: 'per-dimas', at: t('2026-08-18', '10:00') },
    estimatedMin: 120,
    downtime: true,
    parts: BEARING_PARTS,
    values: bearingValues(1.9),
    failure: { problem: 'PRB-VB', mode: 'FM-BW', cause: 'CS-LB', remedy: 'RM-RP', note: 'Both 6204 bearings dry, grease dark and hard. Seal lip worn.' },
    completionNote: 'Replaced drive bearings and seal. Run test 1.9 mm/s.',
    photos: 2,
  },
  {
    key: 'pol03-b2',
    asset: 'POL-03',
    title: 'Rough noise from Poles-03 again',
    description: 'Operator reports the same noise as in August.',
    type: 'corrective',
    priority: 'P2',
    status: 'closed',
    request: 'mr-pol03-0902',
    plan: 'JP-POL-003',
    team: 'team-bdg-mech',
    assignees: ['per-budi'],
    requestedBy: 'per-hendra',
    requestedAt: t('2026-09-02', '10:35'),
    assignedAt: t('2026-09-02', '10:40'),
    assignedBy: 'per-hendra',
    startedAt: t('2026-09-02', '11:05'),
    completedAt: t('2026-09-02', '13:40'),
    verified: { by: 'per-hendra', at: t('2026-09-02', '14:30') },
    closed: { by: 'per-dimas', at: t('2026-09-03', '09:00') },
    estimatedMin: 120,
    downtime: true,
    parts: BEARING_PARTS,
    values: bearingValues(2.0),
    failure: { problem: 'PRB-NS', mode: 'FM-BW', cause: 'CS-LB', remedy: 'RM-RP', note: 'Outer race pitted. Same failure as 17 Aug. Lubrication interval looks too long.' },
    completionNote: 'Second bearing change in 16 days. Asked Hendra to open an RCA.',
    extraEvents: [{ at: t('2026-09-03', '08:30'), by: 'per-hendra', kind: 'comment', text: 'Repeat failure inside 30 days. Opened RCA-2026-004.' }],
    photos: 1,
  },
  {
    key: 'pol03-b3',
    asset: 'POL-03',
    title: 'Planned bearing change during Sunday shutdown',
    description: 'Inspection on 14 Sep showed 5.4 mm/s. Change bearings and take shaft measurements for the RCA.',
    type: 'corrective',
    priority: 'P2',
    status: 'verified',
    request: 'mr-pol03-insp-0914',
    plan: 'JP-POL-003',
    team: 'team-bdg-mech',
    assignees: ['per-budi', 'per-andi'],
    requestedBy: 'per-hendra',
    requestedAt: t('2026-09-19', '16:00'),
    assignedAt: t('2026-09-19', '16:05'),
    assignedBy: 'per-hendra',
    scheduledAt: t('2026-09-20', '08:00'),
    dueAt: t('2026-09-20', '17:00'),
    startedAt: t('2026-09-20', '08:10'),
    completedAt: t('2026-09-20', '16:10'),
    verified: { by: 'per-hendra', at: t('2026-09-21', '08:30'), note: 'Run test OK at 2.1 mm/s. Keep the weekly vibration check.' },
    estimatedMin: 240,
    parts: [...BEARING_PARTS, { code: 'GRS-EP2', qty: 1, status: 'consumed' }],
    values: bearingValues(2.1),
    failure: { problem: 'PRB-VB', mode: 'FM-BW', cause: 'CS-LB', remedy: 'RM-RP', note: 'Third bearing failure. Grease found in one bearing only. Shaft within tolerance.' },
    completionNote: 'Bearings and seal replaced, shaft measured for the RCA (28.002 mm, OK).',
    photos: 3,
  },
  {
    key: 'pol03-inv',
    asset: 'POL-03',
    title: 'Inverter overheat alarm',
    type: 'corrective',
    priority: 'P2',
    status: 'closed',
    team: 'team-bdg-elec',
    assignees: ['per-wahyu'],
    requestedBy: 'per-yusuf',
    requestedAt: t('2026-03-16', '10:20'),
    assignedBy: 'per-yusuf',
    startedAt: t('2026-03-16', '10:50'),
    completedAt: t('2026-03-16', '12:05'),
    verified: { by: 'per-yusuf', at: t('2026-03-16', '15:00') },
    closed: { by: 'per-dimas', at: t('2026-03-17', '09:00') },
    estimatedMin: 60,
    downtime: true,
    parts: [{ code: 'FAN-INV', qty: 1, status: 'consumed' }],
    failure: { problem: 'PRB-TR', mode: 'FM-VF', cause: 'CS-CT', remedy: 'RM-RP', note: 'Cooling fan seized, heatsink full of polishing dust.' },
    completionNote: 'Fan replaced under warranty, claim sent to XYZ.',
  },
  {
    key: 'rob01-io',
    asset: 'ROB-01',
    title: 'Controller I/O board fault',
    type: 'corrective',
    priority: 'P2',
    status: 'closed',
    team: 'team-bdg-elec',
    assignees: ['per-wahyu'],
    requestedBy: 'per-yusuf',
    requestedAt: t('2026-02-09', '09:10'),
    assignedBy: 'per-yusuf',
    startedAt: t('2026-02-09', '09:40'),
    completedAt: t('2026-02-10', '15:30'),
    closed: { by: 'per-dimas', at: t('2026-02-11', '08:30') },
    estimatedMin: 240,
    downtime: true,
    execution: 'mixed',
    labor: [
      { person: 'per-wahyu', start: t('2026-02-09', '09:40'), end: t('2026-02-09', '11:30') },
      { person: 'per-wahyu', start: t('2026-02-10', '13:30'), end: t('2026-02-10', '15:30') },
    ],
    failure: { problem: 'PRB-ST', mode: 'FM-PL', cause: 'CS-EF', remedy: 'RM-RP', note: 'I/O board replaced by Epson engineer under warranty.' },
    completionNote: 'Epson replaced the I/O board. Program restored from backup.',
  },
]

// ─── Requests tied to the scripted history ──────────────────────

export const scriptedRequests: MrSpec[] = [
  {
    key: 'mr-pol03-insp-0810',
    asset: 'POL-03',
    title: 'Inspection warning: vibration 4.8 mm/s, bearing noise rough',
    severity: 'medium',
    status: 'monitor',
    source: 'inspection',
    reportedBy: 'per-andi',
    reportedAt: t('2026-08-10', '15:02'),
    inspectionWo: 'pm-pm-0006-2026-08-10',
    triageNote: 'Monitor at next weekly inspection. Grease added.',
    triagedBy: 'per-hendra',
    triagedAt: t('2026-08-10', '16:00'),
  },
  {
    key: 'mr-pol03-insp-0817',
    asset: 'POL-03',
    title: 'Inspection fail: vibration 7.4 mm/s, loud bearing noise',
    severity: 'high',
    impact: 'reduced',
    status: 'converted',
    source: 'inspection',
    reportedBy: 'per-andi',
    reportedAt: t('2026-08-17', '15:01'),
    inspectionWo: 'pm-pm-0006-2026-08-17',
    wo: 'pol03-b1',
    triagedBy: 'per-hendra',
    triagedAt: t('2026-08-17', '15:05'),
  },
  {
    key: 'mr-pol03-0902',
    asset: 'POL-03',
    title: 'Poles-03 bunyi kasar lagi',
    description: 'Suara dari arah motor kasar lagi seperti bulan lalu.',
    severity: 'high',
    impact: 'reduced',
    status: 'converted',
    reportedBy: 'per-asep',
    reportedAt: t('2026-09-02', '10:20'),
    wo: 'pol03-b2',
    triagedBy: 'per-hendra',
    triagedAt: t('2026-09-02', '10:35'),
    photos: 1,
  },
  {
    key: 'mr-pol03-insp-0914',
    asset: 'POL-03',
    title: 'Inspection warning: vibration 5.4 mm/s, temperature 70 °C',
    severity: 'medium',
    status: 'converted',
    source: 'inspection',
    reportedBy: 'per-andi',
    reportedAt: t('2026-09-14', '15:02'),
    inspectionWo: 'pm-pm-0006-2026-09-14',
    wo: 'pol03-b3',
    triageNote: 'Plan the bearing change for the Sunday shutdown on 20 Sep.',
    triagedBy: 'per-hendra',
    triagedAt: t('2026-09-19', '16:00'),
  },
]

// ─── Open and recent work at 22 Sep 2026, 09:41 ─────────────────

const noteCheck = (label: string): Task => ({ label, type: 'check', required: true })

export const currentWork: WoSpec[] = [
  {
    key: 'pol03-today',
    asset: 'POL-03',
    title: 'High vibration on spindle',
    description: 'Operator reports rough spindle noise and vibration felt on the work table. Fourth vibration complaint on this machine since August.',
    type: 'corrective',
    priority: 'P2',
    status: 'assigned',
    request: 'mr-pol03-today',
    team: 'team-bdg-mech',
    assignees: ['per-budi', 'per-andi'],
    requestedBy: 'per-hendra',
    requestedAt: t('2026-09-22', '08:12'),
    assignedAt: t('2026-09-22', '08:20'),
    assignedBy: 'per-hendra',
    dueAt: t('2026-09-22', '12:00'),
    estimatedMin: 120,
    parts: [
      { code: 'BRG-6204', qty: 2, status: 'reserved' },
      { code: 'SEL-ABC', qty: 1, status: 'reserved' },
    ],
    requiredTools: ['Vibration meter', 'Bearing puller'],
    tasks: [
      { label: 'Listen to spindle and motor bearings', type: 'choice', required: true, options: ['Normal', 'Rough', 'Loud'] },
      { label: 'Spindle vibration at drive end', type: 'measurement', required: true, unit: 'mm/s', max: 7.1, warnMax: 4.5, min: null, warnMin: null },
      { label: 'Belt tension and pulley alignment', type: 'passfail', required: true },
      { label: 'Coupling and motor mounting bolts', type: 'passfail', required: true },
      { label: 'Photo of findings', type: 'photo', required: false },
    ],
  },
  {
    key: 'cnv02-p1',
    asset: 'CNV-02',
    title: 'Coating conveyor stopped, drive chain snapped',
    description: 'Chain came off the drive sprocket and snapped. Coating line stopped, parts waiting in Oven 1 queue.',
    type: 'emergency',
    priority: 'P1',
    status: 'assigned',
    request: 'mr-cnv02-today',
    team: 'team-bdg-mech',
    assignees: ['per-budi'],
    requestedBy: 'per-hendra',
    requestedAt: t('2026-09-22', '09:24'),
    assignedAt: t('2026-09-22', '09:38'),
    assignedBy: 'per-hendra',
    dueAt: t('2026-09-22', '13:20'),
    estimatedMin: 90,
    downtime: true,
    parts: [{ code: 'CHN-RS60', qty: 1, status: 'reserved' }],
    requiredTools: ['Hydraulic jack'],
    safety: {
      loto: true,
      lotoIds: ['sf-elec-iso', 'sf-mech-block'],
      permitIds: ['sf-loto-auth'],
      hazardIds: ['sf-entangle', 'sf-rotating'],
      ppeIds: ['sf-gloves', 'sf-shoes', 'sf-glasses'],
      notes: 'Lock out the drive and the take-up unit.',
    },
    tasks: [
      noteCheck('Lock out conveyor drive and take-up'),
      { label: 'Sprocket teeth condition', type: 'passfail', required: true },
      noteCheck('Fit new chain and set tension'),
      { label: 'Run test for 10 minutes', type: 'passfail', required: true },
    ],
  },
  {
    key: 'ovn02-wait',
    asset: 'OVN-02',
    title: 'Zone 2 temperature reading unstable',
    description: 'QC reports adhesion test failures. Zone 2 swings about 8 °C around setpoint.',
    type: 'corrective',
    priority: 'P2',
    status: 'waiting',
    waitingReason: 'spare_part',
    waitingSince: t('2026-09-20', '16:25'),
    waitingNote: 'Thermocouple TCK-K out of stock, PO-2026-0418 due 24 Sep',
    request: 'mr-ovn02',
    team: 'team-bdg-inst',
    assignees: ['per-wahyu'],
    requestedBy: 'per-yusuf',
    requestedAt: t('2026-09-20', '14:30'),
    assignedAt: t('2026-09-20', '14:45'),
    assignedBy: 'per-yusuf',
    startedAt: t('2026-09-20', '15:05'),
    labor: [{ person: 'per-wahyu', start: t('2026-09-20', '15:05'), end: t('2026-09-20', '16:20') }],
    estimatedMin: 240,
    downtime: false,
    parts: [{ code: 'TCK-K', qty: 1, status: 'reserved' }],
    requiredTools: ['Multimeter', 'Thermal gun'],
    tasks: [
      { label: 'Zone 2 thermocouple deviation from reference', type: 'measurement', required: true, unit: '°C', max: 5, warnMax: 3, min: null, warnMin: null },
      { label: 'Thermocouple wiring and connector', type: 'passfail', required: true },
      noteCheck('Replace zone 2 thermocouple'),
      { label: 'Zone 2 temperature at 180 °C setpoint', type: 'measurement', required: true, unit: '°C', min: 175, max: 185, warnMin: 177, warnMax: 183 },
    ],
    done: 2,
    values: { 0: 9.5, 1: 'pass' },
    failure: { problem: 'PRB-QD', mode: 'FM-SF', cause: 'CS-AG', note: 'Thermocouple reads 9.5 °C low against the reference probe.' },
  },
  {
    key: 'cmp01-vendor',
    asset: 'CMP-01',
    title: 'Oil carry-over into compressed air line',
    description: 'Oil found at the painting booth air filters. Separator element and scavenge line suspected.',
    type: 'corrective',
    priority: 'P2',
    status: 'waiting',
    waitingReason: 'vendor',
    waitingSince: t('2026-09-02', '15:40'),
    waitingNote: 'ABC to bring the overhaul kit, visit booked for 24 Sep',
    request: 'mr-cmp01',
    team: 'team-bdg-utl',
    assignees: ['per-taufik'],
    requestedBy: 'per-hendra',
    requestedAt: t('2026-09-01', '10:05'),
    assignedAt: t('2026-09-02', '09:20'),
    assignedBy: 'per-hendra',
    approval: {
      level: 'manager',
      status: 'approved',
      reason: 'Estimated cost Rp 16,45 jt is above Rp 10 jt.',
      by: 'per-rina',
      at: t('2026-09-02', '09:10'),
      note: 'Go ahead with ABC, ask for the separator warranty.',
    },
    startedAt: t('2026-09-02', '13:00'),
    labor: [{ person: 'per-taufik', start: t('2026-09-02', '13:00'), end: t('2026-09-02', '15:30') }],
    estimatedMin: 480,
    execution: 'vendor',
    vendor: 'ven-abc',
    vendorCost: 12_500_000,
    parts: [{ code: 'SEP-37', qty: 1, status: 'reserved' }],
    tasks: [
      noteCheck('Check oil level and scavenge line sight glass'),
      { label: 'Oil carry-over test with white cloth', type: 'passfail', required: true },
      noteCheck('Vendor replaces separator and overhauls scavenge line'),
      { label: 'Carry-over after repair', type: 'passfail', required: true },
    ],
    done: 2,
    values: { 1: 'fail' },
    failure: { problem: 'PRB-QD', mode: 'FM-SD', cause: 'CS-AG', note: 'Separator element saturated, scavenge line orifice partly blocked.' },
  },
  {
    key: 'pol02-guard',
    asset: 'POL-02',
    title: 'Replace cracked polishing head guard',
    description: 'Right side guard cracked near the hinge.',
    type: 'corrective',
    priority: 'P3',
    status: 'assigned',
    request: 'mr-pol02-guard',
    team: 'team-bdg-mech',
    assignees: ['per-agus'],
    requestedBy: 'per-hendra',
    requestedAt: t('2026-09-16', '10:30'),
    assignedAt: t('2026-09-16', '11:00'),
    assignedBy: 'per-hendra',
    estimatedMin: 120,
    tasks: [noteCheck('Remove cracked guard'), noteCheck('Weld reinforcement plate or fit new guard'), { label: 'Guard interlock test', type: 'passfail', required: true }],
    requiredTools: [],
  },
  {
    key: 'hpr01-draft',
    asset: 'HPR-01',
    title: 'Hydraulic oil seepage at main cylinder',
    description: 'Small puddle under the press every morning. Rod seal suspected. Needs a planned stop and PT Hidrolik Jaya for the reseal.',
    type: 'corrective',
    priority: 'P2',
    status: 'draft',
    request: 'mr-hpr01',
    team: 'team-bdg-mech',
    assignees: ['per-rizky'],
    requestedBy: 'per-dimas',
    requestedAt: t('2026-09-22', '09:05'),
    estimatedMin: 360,
    execution: 'mixed',
    vendor: 'ven-hidrolik',
    vendorCost: 4_500_000,
    parts: [
      { code: 'SEL-HYD-200', qty: 1, status: 'reserved' },
      { code: 'OIL-HYD-46', qty: 40, status: 'reserved' },
    ],
    approval: { level: 'manager', status: 'pending', reason: 'Estimated cost Rp 12,77 jt is above Rp 10 jt.' },
    requiredTools: ['Torque wrench', 'Hydraulic jack'],
    tasks: [
      noteCheck('Block the ram and lock out the hydraulic unit'),
      noteCheck('Vendor reseals the main cylinder'),
      { label: 'Pressure test at 210 bar for 10 minutes', type: 'passfail', required: true },
      { label: 'Two-hand control and light curtain test', type: 'passfail', required: true },
    ],
  },
  {
    key: 'cnc01-draft',
    asset: 'CNC-01',
    title: 'Chip conveyor jam sensor gives false alarms',
    description: 'Machine stops 3 to 4 times per shift with a chip jam alarm while the conveyor is clear.',
    type: 'corrective',
    priority: 'P2',
    status: 'draft',
    team: 'team-bdg-elec',
    assignees: ['per-eko'],
    requestedBy: 'per-dimas',
    requestedAt: t('2026-09-21', '16:20'),
    estimatedMin: 60,
    parts: [{ code: 'PRX-M18', qty: 1, status: 'reserved' }],
    approval: { level: 'supervisor', status: 'pending', reason: 'P2 work orders need supervisor approval.' },
  },
  {
    key: 'pol01-pm',
    asset: 'POL-01',
    title: 'Polishing Machine Monthly PM',
    type: 'preventive',
    priority: 'P3',
    status: 'assigned',
    pm: 'PM-0001',
    plan: 'JP-POL-002',
    team: 'team-bdg-mech',
    assignees: ['per-budi'],
    requestedBy: 'system',
    requestedAt: t('2026-09-19', '06:00'),
    assignedAt: t('2026-09-19', '07:30'),
    assignedBy: 'per-dimas',
    scheduledAt: t('2026-09-22', '13:00'),
    dueAt: t('2026-09-22', '17:00'),
    estimatedMin: 90,
    parts: [{ code: 'GRS-EP2', qty: 1, status: 'reserved' }],
  },
  {
    key: 'pol02-insp',
    asset: 'POL-02',
    title: 'Motor Inspection',
    type: 'inspection',
    priority: 'P3',
    status: 'assigned',
    pm: 'PM-0005',
    plan: 'JP-POL-001',
    team: 'team-bdg-mech',
    assignees: ['per-budi'],
    requestedBy: 'system',
    requestedAt: t('2026-09-21', '06:00'),
    assignedAt: t('2026-09-21', '07:30'),
    assignedBy: 'per-dimas',
    scheduledAt: t('2026-09-22', '10:30'),
    dueAt: t('2026-09-22', '17:00'),
    estimatedMin: 30,
  },
  {
    key: 'ovn01-pm',
    asset: 'OVN-01',
    title: 'Oven Burner Service',
    type: 'preventive',
    priority: 'P3',
    status: 'assigned',
    pm: 'PM-0007',
    plan: 'JP-OVN-001',
    team: 'team-bdg-mech',
    assignees: ['per-rizky'],
    requestedBy: 'system',
    requestedAt: t('2026-09-21', '06:00'),
    assignedAt: t('2026-09-21', '08:00'),
    assignedBy: 'per-dimas',
    scheduledAt: t('2026-09-23', '08:00'),
    dueAt: t('2026-09-24', '17:00'),
    estimatedMin: 120,
  },
  {
    key: 'cnc01-pm',
    asset: 'CNC-01',
    title: 'CNC Lathe Quarterly PM',
    type: 'preventive',
    priority: 'P3',
    status: 'in_progress',
    pm: 'PM-0009',
    plan: 'JP-CNC-001',
    team: 'team-bdg-mech',
    assignees: ['per-rizky'],
    requestedBy: 'system',
    requestedAt: t('2026-09-17', '06:00'),
    assignedAt: t('2026-09-17', '08:10'),
    assignedBy: 'per-dimas',
    scheduledAt: t('2026-09-22', '08:00'),
    dueAt: t('2026-09-22', '17:00'),
    startedAt: t('2026-09-22', '08:05'),
    labor: [{ person: 'per-rizky', start: t('2026-09-22', '08:05'), end: null }],
    estimatedMin: 180,
    done: 4,
    values: { 1: 6.2, 2: 20, 3: 0.004 },
    toolCodes: ['VB-01', 'DG-01'],
    parts: [{ code: 'FLT-HYD', qty: 1, status: 'issued' }],
  },
  {
    key: 'pnl02-pm',
    asset: 'PNL-02',
    title: 'Panel Thermography and Tightening',
    type: 'preventive',
    priority: 'P3',
    status: 'in_progress',
    pm: 'PM-0020',
    plan: 'JP-PNL-001',
    team: 'team-bdg-elec',
    assignees: ['per-wahyu'],
    requestedBy: 'system',
    requestedAt: t('2026-09-13', '06:00'),
    assignedAt: t('2026-09-14', '08:00'),
    assignedBy: 'per-yusuf',
    scheduledAt: t('2026-09-22', '09:00'),
    dueAt: t('2026-09-20', '17:00'),
    startedAt: t('2026-09-22', '09:10'),
    labor: [{ person: 'per-wahyu', start: t('2026-09-22', '09:10'), end: null }],
    estimatedMin: 150,
    done: 1,
    values: { 0: 6.5 },
    toolCodes: ['IR-01'],
  },
  {
    key: 'dry01-corr',
    asset: 'DRY-01',
    title: 'Dew point alarm high, +12 °C',
    type: 'corrective',
    priority: 'P3',
    status: 'in_progress',
    request: 'mr-dry01',
    team: 'team-bdg-utl',
    assignees: ['per-taufik'],
    requestedBy: 'per-taufik',
    requestedAt: t('2026-09-22', '07:50'),
    assignedAt: t('2026-09-22', '08:00'),
    assignedBy: 'per-hendra',
    startedAt: t('2026-09-22', '08:30'),
    labor: [{ person: 'per-taufik', start: t('2026-09-22', '08:30'), end: null }],
    estimatedMin: 120,
    toolCodes: ['MM-01'],
    tasks: [
      { label: 'Refrigerant suction pressure', type: 'measurement', required: true, unit: 'bar', min: 2.5, max: 5, warnMin: 3, warnMax: 4.5 },
      noteCheck('Clean condenser fins'),
      noteCheck('Check the condensate drain valve'),
      { label: 'Dew point after 30 minutes', type: 'measurement', required: true, unit: '°C', max: 7, warnMax: 5, min: null, warnMin: null },
    ],
    done: 1,
    values: { 0: 2.8 },
  },
  {
    key: 'inj01-pm',
    asset: 'INJ-01',
    title: 'Injection Molding 50,000 Shot PM',
    type: 'preventive',
    priority: 'P3',
    status: 'waiting',
    waitingReason: 'production',
    waitingSince: t('2026-09-20', '09:00'),
    waitingNote: 'Customer order runs until Thursday, PM booked for the night shift on 24 Sep',
    pm: 'PM-0014',
    plan: 'JP-INJ-001',
    team: 'team-bdg-mech',
    assignees: ['per-joko'],
    requestedBy: 'system',
    requestedAt: t('2026-09-19', '06:00'),
    assignedAt: t('2026-09-19', '08:00'),
    assignedBy: 'per-dimas',
    scheduledAt: t('2026-09-24', '23:00'),
    dueAt: t('2026-09-21', '17:00'),
    estimatedMin: 120,
    safetyConfirmed: false,
  },
  {
    key: 'hpr02-pm',
    asset: 'HPR-02',
    title: 'Hydraulic Press Monthly PM',
    type: 'preventive',
    priority: 'P3',
    status: 'open',
    pm: 'PM-0013',
    plan: 'JP-HPR-001',
    team: 'team-bdg-mech',
    assignees: [],
    requestedBy: 'system',
    requestedAt: t('2026-09-16', '06:00'),
    dueAt: t('2026-09-19', '17:00'),
    estimatedMin: 90,
  },
  {
    key: 'flt01-wait',
    asset: 'FLT-01',
    title: 'Mast lowers slowly under load',
    type: 'corrective',
    priority: 'P3',
    status: 'waiting',
    waitingReason: 'external_service',
    waitingSince: t('2026-09-12', '14:10'),
    waitingNote: 'Toyota dealer to replace the lift cylinder packing',
    request: 'mr-flt01',
    team: 'team-bdg-mech',
    assignees: ['per-rizky'],
    requestedBy: 'per-hendra',
    requestedAt: t('2026-09-12', '09:40'),
    assignedAt: t('2026-09-12', '10:00'),
    assignedBy: 'per-hendra',
    startedAt: t('2026-09-12', '13:00'),
    labor: [{ person: 'per-rizky', start: t('2026-09-12', '13:00'), end: t('2026-09-12', '14:05') }],
    estimatedMin: 180,
    execution: 'vendor',
    vendorCost: 2_750_000,
  },
  {
    key: 'chl01-wait',
    asset: 'CHL-01',
    title: 'Compressor 2 trips on high discharge pressure',
    type: 'corrective',
    priority: 'P2',
    status: 'waiting',
    waitingReason: 'vendor',
    waitingSince: t('2026-09-14', '15:40'),
    waitingNote: 'ChillerPro to check the condenser fan motor',
    request: 'mr-chl01',
    team: 'team-bdg-utl',
    assignees: ['per-taufik'],
    requestedBy: 'per-hendra',
    requestedAt: t('2026-09-14', '13:40'),
    assignedAt: t('2026-09-14', '13:50'),
    assignedBy: 'per-hendra',
    startedAt: t('2026-09-14', '14:00'),
    labor: [{ person: 'per-taufik', start: t('2026-09-14', '14:00'), end: t('2026-09-14', '15:30') }],
    estimatedMin: 240,
    execution: 'mixed',
    vendor: 'ven-chillerpro',
    vendorCost: 3_200_000,
    failure: { problem: 'PRB-TR', note: 'Condenser fan 2 runs slow, discharge reaches 262 psi.' },
  },
  {
    key: 'lkt01-corr',
    asset: 'LKT-01',
    title: 'False leak rejects on station 2',
    type: 'corrective',
    priority: 'P3',
    status: 'assigned',
    request: 'mr-lkt01',
    team: 'team-bdg-inst',
    assignees: ['per-lina'],
    requestedBy: 'per-yusuf',
    requestedAt: t('2026-09-21', '11:00'),
    assignedAt: t('2026-09-21', '11:15'),
    assignedBy: 'per-yusuf',
    dueAt: t('2026-09-24', '11:00'),
    estimatedMin: 90,
  },
  {
    key: 'rob01-imp',
    asset: 'ROB-01',
    title: 'Add torque monitoring to screw robot',
    description: 'Log final torque per screw to catch cross-threading before the leak test.',
    type: 'improvement',
    priority: 'P4',
    status: 'open',
    team: 'team-bdg-elec',
    assignees: [],
    requestedBy: 'per-dimas',
    requestedAt: t('2026-09-15', '10:00'),
    dueAt: t('2026-10-15', '17:00'),
    estimatedMin: 480,
    miscCost: 1_800_000,
    tasks: [noteCheck('Wire torque controller output to PLC'), noteCheck('Add torque log to HMI'), { label: 'Hand over to production', type: 'signature', required: true }],
  },
  {
    key: 'thovn01-cal',
    asset: 'TH-OVN-01',
    title: 'Oven 1 Reference Thermometer calibration',
    description: 'Calibration expired on 17 Sep. Send to PT Kalibrasi Nusantara.',
    type: 'calibration',
    priority: 'P3',
    status: 'assigned',
    plan: 'JP-CAL-001',
    team: 'team-bdg-inst',
    assignees: ['per-lina'],
    requestedBy: 'per-dimas',
    requestedAt: t('2026-09-18', '09:00'),
    assignedAt: t('2026-09-18', '09:30'),
    assignedBy: 'per-dimas',
    scheduledAt: t('2026-09-24', '09:00'),
    dueAt: t('2026-09-25', '17:00'),
    estimatedMin: 60,
    execution: 'vendor',
    vendor: 'ven-kalibra',
    vendorCost: 450_000,
  },
  {
    key: 'gen01-insp',
    asset: 'GEN-01',
    title: 'Genset Weekly Run Test',
    type: 'inspection',
    priority: 'P3',
    status: 'assigned',
    pm: 'PM-0024',
    plan: 'JP-GEN-001',
    team: 'team-bdg-elec',
    assignees: ['per-eko'],
    requestedBy: 'system',
    requestedAt: t('2026-09-21', '06:00'),
    assignedAt: t('2026-09-21', '07:40'),
    assignedBy: 'per-yusuf',
    scheduledAt: t('2026-09-22', '16:00'),
    dueAt: t('2026-09-22', '23:00'),
    estimatedMin: 30,
  },
  {
    key: 'cnv01-insp',
    asset: 'CNV-01',
    title: 'Conveyor Weekly Inspection',
    type: 'inspection',
    priority: 'P3',
    status: 'assigned',
    pm: 'PM-0021',
    plan: 'JP-CNV-001',
    team: 'team-bdg-mech',
    assignees: ['per-andi'],
    requestedBy: 'system',
    requestedAt: t('2026-09-22', '06:00'),
    assignedAt: t('2026-09-22', '07:30'),
    assignedBy: 'per-dimas',
    scheduledAt: t('2026-09-23', '09:00'),
    dueAt: t('2026-09-23', '17:00'),
    estimatedMin: 20,
  },
  {
    key: 'ovn01-done',
    asset: 'OVN-01',
    title: 'Burner fails to ignite on restart',
    type: 'corrective',
    priority: 'P2',
    status: 'completed',
    request: 'mr-ovn01',
    team: 'team-bdg-mech',
    assignees: ['per-rizky'],
    requestedBy: 'per-hendra',
    requestedAt: t('2026-09-21', '11:20'),
    assignedAt: t('2026-09-21', '11:30'),
    assignedBy: 'per-hendra',
    startedAt: t('2026-09-21', '11:45'),
    completedAt: t('2026-09-21', '14:40'),
    estimatedMin: 120,
    downtime: true,
    parts: [{ code: 'NZL-BRN', qty: 1, status: 'consumed' }],
    failure: { problem: 'PRB-ST', mode: 'FM-BN', cause: 'CS-CT', remedy: 'RM-RP', note: 'Nozzle carboned, electrode gap 5 mm.' },
    completionNote: 'Replaced nozzle, cleaned electrode, flame signal 6 µA.',
    photos: 2,
  },
  {
    key: 'pnl01-done',
    asset: 'PNL-01',
    title: 'Panel Thermography and Tightening',
    type: 'preventive',
    priority: 'P3',
    status: 'completed',
    pm: 'PM-0019',
    plan: 'JP-PNL-001',
    team: 'team-bdg-elec',
    assignees: ['per-wahyu', 'per-deni'],
    requestedBy: 'system',
    requestedAt: t('2026-09-12', '06:00'),
    assignedAt: t('2026-09-12', '08:00'),
    assignedBy: 'per-yusuf',
    scheduledAt: t('2026-09-19', '12:30'),
    dueAt: t('2026-09-19', '17:00'),
    startedAt: t('2026-09-19', '12:30'),
    completedAt: t('2026-09-19', '15:00'),
    estimatedMin: 150,
    values: { 0: 3.1, 3: 850 },
    completionNote: 'All joints below 4 °C rise. Tightened 24 MCCB terminals.',
  },
  {
    key: 'str01-done',
    asset: 'STR-01',
    title: 'Strap feed jams every few cycles',
    type: 'corrective',
    priority: 'P4',
    status: 'completed',
    request: 'mr-str01',
    team: 'team-bdg-mech',
    assignees: ['per-andi'],
    requestedBy: 'per-hendra',
    requestedAt: t('2026-09-21', '09:10'),
    assignedAt: t('2026-09-21', '09:30'),
    assignedBy: 'per-hendra',
    startedAt: t('2026-09-21', '13:10'),
    completedAt: t('2026-09-21', '14:00'),
    estimatedMin: 60,
    failure: { problem: 'PRB-SM', mode: 'FM-MA', cause: 'CS-WR', remedy: 'RM-AD', note: 'Feed roller gap too wide.' },
    completionNote: 'Adjusted feed roller gap to 0.8 mm.',
  },
  // Factory Cikarang
  {
    key: 'ckr-cmp-leak',
    asset: 'CKR-CMP-01',
    title: 'Oil leak at compressor cooler hose',
    type: 'corrective',
    priority: 'P2',
    status: 'in_progress',
    request: 'mr-ckr-cmp',
    team: 'team-ckr-mnt',
    assignees: ['per-galih'],
    requestedBy: 'per-irfan',
    requestedAt: t('2026-09-22', '08:10'),
    assignedAt: t('2026-09-22', '08:20'),
    assignedBy: 'per-irfan',
    startedAt: t('2026-09-22', '08:40'),
    labor: [{ person: 'per-galih', start: t('2026-09-22', '08:40'), end: null }],
    estimatedMin: 120,
    parts: [{ code: 'HOS-HYD', qty: 1, status: 'issued' }],
    toolCodes: ['CKR-TW-01'],
  },
  {
    key: 'ckr-cnv-eye',
    asset: 'CKR-CNV-01',
    title: 'Photo-eye misaligned, parts not detected',
    type: 'corrective',
    priority: 'P3',
    status: 'waiting',
    waitingReason: 'spare_part',
    waitingSince: t('2026-09-21', '10:30'),
    waitingNote: 'No PRX-M18 left in Warehouse C1, transfer requested from Bandung',
    request: 'mr-ckr-cnv',
    team: 'team-ckr-mnt',
    assignees: ['per-hadi'],
    requestedBy: 'per-irfan',
    requestedAt: t('2026-09-21', '09:00'),
    assignedAt: t('2026-09-21', '09:10'),
    assignedBy: 'per-irfan',
    startedAt: t('2026-09-21', '09:30'),
    labor: [{ person: 'per-hadi', start: t('2026-09-21', '09:30'), end: t('2026-09-21', '10:20') }],
    estimatedMin: 60,
    parts: [{ code: 'PRX-M18', qty: 1, status: 'reserved' }],
  },
  {
    key: 'ckr-vmc-alarm',
    asset: 'CKR-VMC-01',
    title: 'Spindle warm-up alarm at start of shift',
    type: 'corrective',
    priority: 'P2',
    status: 'open',
    request: 'mr-ckr-vmc',
    team: 'team-ckr-mnt',
    assignees: [],
    requestedBy: 'per-irfan',
    requestedAt: t('2026-09-22', '07:25'),
    estimatedMin: 90,
    approval: { level: 'supervisor', status: 'approved', reason: 'P2 work orders need supervisor approval.', by: 'per-irfan', at: t('2026-09-22', '07:30') },
  },
  {
    key: 'ckr-hpr-pm',
    asset: 'CKR-HPR-01',
    title: 'Hydraulic Press Monthly PM',
    type: 'preventive',
    priority: 'P3',
    status: 'assigned',
    pm: 'PM-0027',
    plan: 'JP-HPR-001',
    team: 'team-ckr-mnt',
    assignees: ['per-fikri'],
    requestedBy: 'system',
    requestedAt: t('2026-09-22', '06:00'),
    assignedAt: t('2026-09-22', '07:00'),
    assignedBy: 'per-irfan',
    scheduledAt: t('2026-09-24', '16:00'),
    dueAt: t('2026-09-25', '17:00'),
    estimatedMin: 90,
  },
  {
    key: 'ckr-cnc2-done',
    asset: 'CKR-CNC-02',
    title: 'Tailstock does not retract',
    type: 'corrective',
    priority: 'P3',
    status: 'completed',
    team: 'team-ckr-mnt',
    assignees: ['per-hadi'],
    requestedBy: 'per-irfan',
    requestedAt: t('2026-09-21', '13:00'),
    assignedAt: t('2026-09-21', '13:10'),
    assignedBy: 'per-irfan',
    startedAt: t('2026-09-21', '13:30'),
    completedAt: t('2026-09-21', '14:45'),
    estimatedMin: 60,
    failure: { problem: 'PRB-SM', mode: 'FM-SF', cause: 'CS-CT', remedy: 'RM-CL', note: 'Retract sensor covered in coolant sludge.' },
    completionNote: 'Cleaned the retract sensor and adjusted the target.',
  },
]

export const currentRequests: MrSpec[] = [
  {
    key: 'mr-pol03-today',
    asset: 'POL-03',
    title: 'Spindle noise rougher than usual',
    description: 'Suara spindle lebih kasar dari biasanya, getaran terasa sampai meja kerja.',
    severity: 'medium',
    impact: 'reduced',
    status: 'converted',
    reportedBy: 'per-asep',
    reportedAt: t('2026-09-22', '08:05'),
    wo: 'pol03-today',
    triagedBy: 'per-hendra',
    triagedAt: t('2026-09-22', '08:12'),
    photos: 2,
  },
  {
    key: 'mr-cnv02-today',
    asset: 'CNV-02',
    title: 'Coating conveyor stopped, chain came off',
    description: 'Rantai conveyor lepas dan putus. Line coating berhenti.',
    severity: 'critical',
    impact: 'stopped',
    status: 'converted',
    reportedBy: 'per-asep',
    reportedAt: t('2026-09-22', '09:20'),
    wo: 'cnv02-p1',
    triagedBy: 'per-hendra',
    triagedAt: t('2026-09-22', '09:24'),
    photos: 1,
  },
  {
    key: 'mr-pnl02-smell',
    asset: 'PNL-02',
    title: 'Burning smell near distribution panel',
    description: 'Bau hangus di sekitar panel distribusi produksi, sekitar pukul 09.30.',
    severity: 'high',
    impact: 'none',
    status: 'new',
    reportedBy: 'per-rudi',
    reportedAt: t('2026-09-22', '09:35'),
  },
  {
    key: 'mr-hpr01',
    asset: 'HPR-01',
    title: 'Oil seepage at main cylinder',
    description: 'Ada genangan oli kecil di bawah press setiap pagi.',
    severity: 'high',
    impact: 'none',
    status: 'converted',
    reportedBy: 'per-rudi',
    reportedAt: t('2026-09-22', '07:30'),
    wo: 'hpr01-draft',
    triagedBy: 'per-dimas',
    triagedAt: t('2026-09-22', '09:05'),
    photos: 1,
  },
  {
    key: 'mr-dry01',
    asset: 'DRY-01',
    title: 'Dew point alarm on air dryer',
    severity: 'medium',
    status: 'converted',
    source: 'technician',
    reportedBy: 'per-taufik',
    reportedAt: t('2026-09-22', '07:45'),
    wo: 'dry01-corr',
    triagedBy: 'per-hendra',
    triagedAt: t('2026-09-22', '07:50'),
  },
  {
    key: 'mr-pol01-wobble',
    asset: 'POL-01',
    title: 'Polishing wheel wobbles at high speed',
    description: 'Roda poles goyang saat putaran tinggi.',
    severity: 'medium',
    impact: 'reduced',
    status: 'new',
    reportedBy: 'per-asep',
    reportedAt: t('2026-09-21', '15:10'),
    photos: 1,
  },
  {
    key: 'mr-ovn01',
    asset: 'OVN-01',
    title: 'Oven 1 burner fails to ignite on restart',
    severity: 'high',
    impact: 'stopped',
    status: 'converted',
    reportedBy: 'per-asep',
    reportedAt: t('2026-09-21', '11:10'),
    wo: 'ovn01-done',
    triagedBy: 'per-hendra',
    triagedAt: t('2026-09-21', '11:20'),
  },
  {
    key: 'mr-lkt01',
    asset: 'LKT-01',
    title: 'False leak rejects on station 2',
    description: '12 good parts rejected this morning, retest passes.',
    severity: 'medium',
    impact: 'reduced',
    status: 'converted',
    reportedBy: 'per-dewi',
    reportedAt: t('2026-09-21', '10:15'),
    wo: 'lkt01-corr',
    triagedBy: 'per-yusuf',
    triagedAt: t('2026-09-21', '11:00'),
  },
  {
    key: 'mr-str01',
    asset: 'STR-01',
    title: 'Strap feed jams',
    severity: 'low',
    status: 'converted',
    reportedBy: 'per-dewi',
    reportedAt: t('2026-09-21', '09:00'),
    wo: 'str01-done',
    triagedBy: 'per-hendra',
    triagedAt: t('2026-09-21', '09:10'),
  },
  {
    key: 'mr-ovn02',
    asset: 'OVN-02',
    title: 'Zone 2 temperature swings, adhesion test failed',
    description: 'Hasil cross-cut test gagal di 3 sampel. Suhu zona 2 naik turun sekitar 8 °C.',
    severity: 'high',
    impact: 'reduced',
    status: 'converted',
    reportedBy: 'per-dewi',
    reportedAt: t('2026-09-20', '14:10'),
    wo: 'ovn02-wait',
    triagedBy: 'per-yusuf',
    triagedAt: t('2026-09-20', '14:30'),
    photos: 2,
  },
  {
    key: 'mr-spb01-light',
    asset: 'SPB-01',
    title: 'Booth lighting dim on the left wall',
    severity: 'low',
    status: 'new',
    reportedBy: 'per-dewi',
    reportedAt: t('2026-09-20', '10:05'),
  },
  {
    key: 'mr-cnv01-noise',
    asset: 'CNV-01',
    title: 'Conveyor noisy at tail pulley',
    severity: 'low',
    status: 'monitor',
    reportedBy: 'per-dewi',
    reportedAt: t('2026-09-18', '13:20'),
    triageNote: 'Check at the weekly inspection on 23 Sep.',
    triagedBy: 'per-hendra',
    triagedAt: t('2026-09-18', '14:00'),
  },
  {
    key: 'mr-pol02-guard',
    asset: 'POL-02',
    title: 'Guard cracked on the right side',
    description: 'Guard retak di sisi kanan dekat engsel.',
    severity: 'medium',
    status: 'converted',
    reportedBy: 'per-asep',
    reportedAt: t('2026-09-16', '10:00'),
    wo: 'pol02-guard',
    triagedBy: 'per-hendra',
    triagedAt: t('2026-09-16', '10:30'),
    photos: 1,
  },
  {
    key: 'mr-chl01',
    asset: 'CHL-01',
    title: 'Chiller compressor 2 tripping',
    severity: 'high',
    impact: 'reduced',
    status: 'converted',
    source: 'technician',
    reportedBy: 'per-taufik',
    reportedAt: t('2026-09-14', '13:30'),
    wo: 'chl01-wait',
    triagedBy: 'per-hendra',
    triagedAt: t('2026-09-14', '13:40'),
  },
  {
    key: 'mr-flt01',
    asset: 'FLT-01',
    title: 'Forklift mast lowers slowly',
    severity: 'medium',
    status: 'converted',
    reportedBy: 'per-dewi',
    reportedAt: t('2026-09-12', '09:20'),
    wo: 'flt01-wait',
    triagedBy: 'per-hendra',
    triagedAt: t('2026-09-12', '09:40'),
  },
  {
    key: 'mr-inj02-dryer',
    asset: 'INJ-02',
    title: 'Hopper dryer noisy',
    severity: 'low',
    status: 'rejected',
    reportedBy: 'per-rudi',
    reportedAt: t('2026-09-10', '14:00'),
    triageNote: 'The hopper dryer is covered by the material supplier contract. Forwarded to purchasing.',
    triagedBy: 'per-hendra',
    triagedAt: t('2026-09-10', '15:00'),
  },
  {
    key: 'mr-cmp01',
    asset: 'CMP-01',
    title: 'Oil in compressed air at the painting booth',
    description: 'Filter udara di booth penuh oli.',
    severity: 'high',
    impact: 'reduced',
    status: 'converted',
    reportedBy: 'per-asep',
    reportedAt: t('2026-09-01', '09:40'),
    wo: 'cmp01-vendor',
    triagedBy: 'per-hendra',
    triagedAt: t('2026-09-01', '10:05'),
    photos: 1,
  },
  {
    key: 'mr-cmp01-dup',
    asset: 'CMP-01',
    title: 'Oily air at spray gun',
    severity: 'medium',
    status: 'duplicate',
    reportedBy: 'per-dewi',
    reportedAt: t('2026-09-03', '10:15'),
    duplicateOf: 'mr-cmp01',
    triageNote: 'Same issue as the open compressor work order.',
    triagedBy: 'per-hendra',
    triagedAt: t('2026-09-03', '10:40'),
  },
  {
    key: 'mr-ckr-cmp',
    asset: 'CKR-CMP-01',
    title: 'Oil leak at compressor cooler hose',
    severity: 'high',
    impact: 'none',
    status: 'converted',
    reportedBy: 'per-nina',
    reportedAt: t('2026-09-22', '08:00'),
    wo: 'ckr-cmp-leak',
    triagedBy: 'per-irfan',
    triagedAt: t('2026-09-22', '08:10'),
  },
  {
    key: 'mr-ckr-cnv',
    asset: 'CKR-CNV-01',
    title: 'Parts pass the photo-eye without stopping',
    severity: 'medium',
    status: 'converted',
    reportedBy: 'per-nina',
    reportedAt: t('2026-09-21', '08:40'),
    wo: 'ckr-cnv-eye',
    triagedBy: 'per-irfan',
    triagedAt: t('2026-09-21', '09:00'),
  },
  {
    key: 'mr-ckr-vmc',
    asset: 'CKR-VMC-01',
    title: 'Spindle warm-up alarm',
    severity: 'high',
    status: 'converted',
    reportedBy: 'per-nina',
    reportedAt: t('2026-09-22', '07:15'),
    wo: 'ckr-vmc-alarm',
    triagedBy: 'per-irfan',
    triagedAt: t('2026-09-22', '07:25'),
  },
  {
    key: 'mr-ckr-hpr',
    asset: 'CKR-HPR-01',
    title: 'Press ram drifts down when idle',
    severity: 'high',
    impact: 'none',
    status: 'new',
    reportedBy: 'per-nina',
    reportedAt: t('2026-09-22', '09:05'),
  },
  // older triaged requests that never became work
  {
    key: 'mr-old-1',
    asset: 'CNC-02',
    title: 'Coolant smells bad',
    severity: 'low',
    status: 'rejected',
    reportedBy: 'per-rudi',
    reportedAt: t('2026-06-11', '10:00'),
    triageNote: 'Coolant change is a production housekeeping task.',
    triagedBy: 'per-hendra',
    triagedAt: t('2026-06-11', '13:00'),
  },
  {
    key: 'mr-old-2',
    asset: 'OVN-02',
    title: 'Oven 2 door hard to close',
    severity: 'low',
    status: 'monitor',
    reportedBy: 'per-asep',
    reportedAt: t('2026-08-26', '09:30'),
    triageNote: 'Hinge greased. Watch during the burner service.',
    triagedBy: 'per-hendra',
    triagedAt: t('2026-08-26', '11:00'),
  },
  {
    key: 'mr-old-3',
    asset: 'VMC-01',
    title: 'Chip conveyor noisy',
    severity: 'low',
    status: 'duplicate',
    reportedBy: 'per-rudi',
    reportedAt: t('2026-05-04', '08:30'),
    duplicateOf: 'mr-old-4',
    triageNote: 'Reported twice on the same morning.',
    triagedBy: 'per-hendra',
    triagedAt: t('2026-05-04', '09:30'),
  },
  {
    key: 'mr-old-4',
    asset: 'VMC-01',
    title: 'Chip conveyor squeaks',
    severity: 'low',
    status: 'monitor',
    reportedBy: 'per-rudi',
    reportedAt: t('2026-05-04', '07:50'),
    triageNote: 'Added to the monthly PM checklist.',
    triagedBy: 'per-hendra',
    triagedAt: t('2026-05-04', '09:30'),
  },
  {
    key: 'mr-old-5',
    asset: 'STR-01',
    title: 'Strap tension too loose',
    severity: 'low',
    status: 'rejected',
    reportedBy: 'per-dewi',
    reportedAt: t('2026-02-02', '14:10'),
    triageNote: 'Operator setting, tension reset with the team leader.',
    triagedBy: 'per-hendra',
    triagedAt: t('2026-02-02', '15:00'),
  },
]

// ─── RCA ────────────────────────────────────────────────────────

const empty = { man: [], machine: [], method: [], material: [], measurement: [], environment: [] }
const d = (s: string) => t(s, '09:00')

export function buildRcas(failureKeysBy: (assetCode: string, modeCode: string) => string[]): Rca[] {
  return [
    {
      id: 'rca-2026-004',
      code: 'RCA-2026-004',
      siteId: 'site-bdg',
      title: 'Poles-03 drive bearing fails repeatedly',
      assetId: A('POL-03').id,
      modeId: fcId('FM-BW'),
      trigger: 'repeat',
      status: 'actions',
      ownerId: 'per-hendra',
      createdAt: toIso(t('2026-09-03', '08:30')),
      dueAt: toIso(d('2026-09-30')),
      closedAt: null,
      woIds: ['pol03-b1', 'pol03-b2', 'pol03-b3'],
      problem: 'Bearing 6204 on the Poles-03 drive failed three times in 34 days (17 Aug, 02 Sep, 20 Sep). Each failure stopped the machine for 3 to 8 hours.',
      whys: [
        'The bearings ran with too little grease.',
        'The lubrication interval is too long for the current load.',
        'PM-0003 greases the machine every 30 calendar days.',
        'Machine utilization rose from 12 to 18 hours per day in July.',
      ],
      rootCause: 'The PM interval follows the calendar and no longer matches machine utilization.',
      fishbone: {
        man: ['Shift B operators run the spindle at higher feed'],
        machine: ['6204 bearing runs near its rated load at 18 h/day'],
        method: ['PM triggered by calendar, not runtime', 'SOP does not state grease quantity'],
        material: ['Grease supplier changed in June'],
        measurement: ['Vibration checked by feel until July'],
        environment: ['Polishing dust reaches the seal lip'],
      },
      actions: [
        { id: 'capa-004-1', kind: 'corrective', text: 'Replace both drive bearings and the oil seal', ownerId: 'per-budi', dueAt: toIso(d('2026-09-20')), status: 'done', doneAt: toIso(t('2026-09-20', '16:10')) },
        { id: 'capa-004-2', kind: 'preventive', text: 'Add vibration reading to the weekly motor inspection', ownerId: 'per-dimas', dueAt: toIso(d('2026-09-10')), status: 'done', doneAt: toIso(t('2026-09-08', '10:00')) },
        { id: 'capa-004-3', kind: 'preventive', text: 'Change PM-0003 from every 30 days to every 400 runtime hours', ownerId: 'per-dimas', dueAt: toIso(d('2026-09-25')), status: 'open', doneAt: null },
        { id: 'capa-004-4', kind: 'preventive', text: 'Add grease quantity (8 g per bearing) to JP-POL-002', ownerId: 'per-hendra', dueAt: toIso(d('2026-09-28')), status: 'open', doneAt: null },
        { id: 'capa-004-5', kind: 'corrective', text: 'Brief shift B operators on feed rate limits', ownerId: 'per-rudi', dueAt: toIso(d('2026-10-05')), status: 'open', doneAt: null },
      ],
    },
    {
      id: 'rca-2026-003',
      code: 'RCA-2026-003',
      siteId: 'site-bdg',
      title: 'Oven 2 flame failure lockouts',
      assetId: A('OVN-02').id,
      modeId: fcId('FM-BN'),
      trigger: 'chronic',
      status: 'analysis',
      ownerId: 'per-yusuf',
      createdAt: toIso(d('2026-08-28')),
      dueAt: toIso(d('2026-10-10')),
      closedAt: null,
      woIds: failureKeysBy('OVN-02', 'FM-BN'),
      problem: 'Oven 2 locks out on flame failure several times a month. Each lockout scraps the parts inside the oven.',
      whys: ['The flame detector signal drops below 2 µA.', 'Soot builds up on the detector and the nozzle.', 'The air-fuel ratio drifts rich.'],
      rootCause: '',
      fishbone: {
        ...empty,
        machine: ['Detector lens sooted', 'Damper linkage worn'],
        method: ['No combustion analysis in the monthly service'],
        material: ['LPG supplier changed in May'],
      },
      actions: [
        { id: 'capa-003-1', kind: 'corrective', text: 'Clean detector and nozzle weekly until combustion tuning is done', ownerId: 'per-rizky', dueAt: toIso(d('2026-10-10')), status: 'open', doneAt: null },
        { id: 'capa-003-2', kind: 'preventive', text: 'Book Oven Tech for combustion analysis and tuning', ownerId: 'per-dimas', dueAt: toIso(d('2026-09-30')), status: 'open', doneAt: null },
      ],
    },
    {
      id: 'rca-2026-002',
      code: 'RCA-2026-002',
      siteId: 'site-bdg',
      title: 'Compressor 01 high temperature trips',
      assetId: A('CMP-01').id,
      modeId: fcId('FM-CL'),
      trigger: 'high_cost',
      status: 'closed',
      ownerId: 'per-hendra',
      createdAt: toIso(d('2026-06-01')),
      dueAt: toIso(d('2026-07-15')),
      closedAt: toIso(d('2026-07-14')),
      woIds: [...failureKeysBy('CMP-01', 'FM-CL'), 'imp-6'],
      problem: 'Compressor 01 tripped on element temperature 4 times in May and stopped plant air.',
      whys: [
        'Element outlet reached 110 °C and tripped.',
        'Oil cooler airflow was blocked.',
        'The compressor room intake filter was clogged with dust.',
        'Room intake cleaning was not in the PM.',
      ],
      rootCause: 'Compressor room ventilation was outside the PM scope.',
      fishbone: { ...empty, method: ['No task for the room intake filter'], environment: ['Dry season dust from the road side'] },
      actions: [
        { id: 'capa-002-1', kind: 'corrective', text: 'Clean cooler and room intake filter', ownerId: 'per-taufik', dueAt: toIso(d('2026-06-03')), status: 'done', doneAt: toIso(d('2026-06-02')) },
        { id: 'capa-002-2', kind: 'preventive', text: 'Add room intake cleaning to JP-CMP-001', ownerId: 'per-dimas', dueAt: toIso(d('2026-06-15')), status: 'done', doneAt: toIso(d('2026-06-12')) },
        { id: 'capa-002-3', kind: 'preventive', text: 'Replace manual drain with zero-loss drain', ownerId: 'per-taufik', dueAt: toIso(d('2026-07-10')), status: 'done', doneAt: toIso(d('2026-07-06')) },
      ],
    },
    {
      id: 'rca-2026-001',
      code: 'RCA-2026-001',
      siteId: 'site-bdg',
      title: 'Light curtain bypass found on Press 200T',
      assetId: A('HPR-01').id,
      modeId: null,
      trigger: 'safety',
      status: 'closed',
      ownerId: 'per-hendra',
      createdAt: toIso(d('2026-03-05')),
      dueAt: toIso(d('2026-04-30')),
      closedAt: toIso(d('2026-04-28')),
      woIds: ['imp-4'],
      problem: 'During the March PM the light curtain on HPR-01 was found bridged with a jumper wire.',
      whys: [
        'An operator bridged the light curtain to clear jams faster.',
        'Blanks jammed several times per shift.',
        'Worn die guide pins misfed the blanks.',
        'Guide pins were not in the PM checklist.',
      ],
      rootCause: 'Die guide pins were never inspected, so jams pushed operators to bypass the guard.',
      fishbone: { ...empty, man: ['Pressure to hit output'], method: ['Guide pins missing from PM'], machine: ['Type 2 curtain easy to bridge'] },
      actions: [
        { id: 'capa-001-1', kind: 'corrective', text: 'Remove the jumper and retrain the crew', ownerId: 'per-hendra', dueAt: toIso(d('2026-03-06')), status: 'done', doneAt: toIso(d('2026-03-05')) },
        { id: 'capa-001-2', kind: 'preventive', text: 'Upgrade light curtain to Type 4 with muting', ownerId: 'per-yusuf', dueAt: toIso(d('2026-04-30')), status: 'done', doneAt: toIso(d('2026-04-20')) },
        { id: 'capa-001-3', kind: 'preventive', text: 'Add guide pin check to JP-HPR-001', ownerId: 'per-dimas', dueAt: toIso(d('2026-03-31')), status: 'done', doneAt: toIso(d('2026-03-20')) },
      ],
    },
    {
      id: 'rca-2026-005',
      code: 'RCA-2026-005',
      siteId: 'site-ckr',
      title: 'Repeated oil leaks at CK compressor cooler',
      assetId: A('CKR-CMP-01').id,
      modeId: fcId('FM-SD'),
      trigger: 'repeat',
      status: 'open',
      ownerId: 'per-irfan',
      createdAt: toIso(d('2026-09-15')),
      dueAt: toIso(d('2026-10-15')),
      closedAt: null,
      woIds: [...failureKeysBy('CKR-CMP-01', 'FM-SD'), 'ckr-cmp-leak'],
      problem: 'The cooler hose and fittings on CKR-CMP-01 leaked oil three times this year.',
      whys: [],
      rootCause: '',
      fishbone: empty,
      actions: [],
    },
  ]
}

export const warrantyClaims: WarrantyClaim[] = [
  {
    id: 'wc-1',
    assetId: A('POL-03').id,
    vendorId: 'ven-xyz',
    woId: 'pol03-b3',
    date: toIso(t('2026-09-21', '10:00')),
    status: 'submitted',
    description: 'Third drive bearing failure in 34 days. Requesting an OEM check of the bearing fits under warranty.',
    amount: 1_250_000,
  },
  {
    id: 'wc-2',
    assetId: A('POL-03').id,
    vendorId: 'ven-xyz',
    woId: 'pol03-inv',
    date: toIso(t('2026-03-17', '10:00')),
    status: 'approved',
    description: 'Inverter cooling fan seized after 21 months.',
    amount: 420_000,
  },
  {
    id: 'wc-3',
    assetId: A('ROB-01').id,
    vendorId: null,
    woId: 'rob01-io',
    date: toIso(t('2026-02-10', '16:00')),
    status: 'approved',
    description: 'Controller I/O board replaced by Epson.',
    amount: 8_500_000,
  },
]

