import type {
  AssetType,
  Company,
  CostCenter,
  FailureCode,
  Location,
  NotificationChannel,
  NotificationEvent,
  NotificationRule,
  Part,
  Person,
  Role,
  SafetyItem,
  Settings,
  Site,
  Skill,
  SkillLevel,
  Team,
  TechnicianProfile,
  Vendor,
  Warehouse,
} from '../../packages/types/src/index.ts'

export const company: Company = { id: 'co-nusa', name: 'PT Nusa Presisi Manufaktur' }

export const sites: Site[] = [
  { id: 'site-bdg', code: 'BDG', name: 'Factory Bandung', city: 'Bandung' },
  { id: 'site-ckr', code: 'CKR', name: 'Factory Cikarang', city: 'Bekasi' },
]

const loc = (id: string, siteId: string, parentId: string | null, kind: Location['kind'], code: string, name: string): Location => ({
  id,
  siteId,
  parentId,
  kind,
  code,
  name,
})

export const locations: Location[] = [
  loc('loc-bdg-prd', 'site-bdg', null, 'plant', 'PRD', 'Production'),
  loc('loc-bdg-mch', 'site-bdg', 'loc-bdg-prd', 'area', 'MCH', 'Machining'),
  loc('loc-bdg-cnc', 'site-bdg', 'loc-bdg-mch', 'line', 'CNC', 'CNC Cell'),
  loc('loc-bdg-prs', 'site-bdg', 'loc-bdg-mch', 'line', 'PRS', 'Press Line'),
  loc('loc-bdg-mld', 'site-bdg', 'loc-bdg-mch', 'line', 'MLD', 'Molding Line'),
  loc('loc-bdg-fin', 'site-bdg', 'loc-bdg-prd', 'area', 'FIN', 'Finishing'),
  loc('loc-bdg-pol', 'site-bdg', 'loc-bdg-fin', 'line', 'POL', 'Polishing Area'),
  loc('loc-bdg-ctg', 'site-bdg', 'loc-bdg-fin', 'line', 'CTG', 'Coating Line'),
  loc('loc-bdg-asm', 'site-bdg', 'loc-bdg-prd', 'area', 'ASM', 'Assembly'),
  loc('loc-bdg-as1', 'site-bdg', 'loc-bdg-asm', 'line', 'AS1', 'Assembly Line 1'),
  loc('loc-bdg-pck', 'site-bdg', 'loc-bdg-asm', 'line', 'PCK', 'Packing'),
  loc('loc-bdg-utl', 'site-bdg', null, 'plant', 'UTL', 'Utility'),
  loc('loc-bdg-cmp', 'site-bdg', 'loc-bdg-utl', 'area', 'CMP', 'Compressor House'),
  loc('loc-bdg-elr', 'site-bdg', 'loc-bdg-utl', 'area', 'ELR', 'Electrical Room'),
  loc('loc-bdg-cwt', 'site-bdg', 'loc-bdg-utl', 'area', 'CWT', 'Chiller & Water'),
  loc('loc-ckr-prd', 'site-ckr', null, 'plant', 'PRD', 'Production'),
  loc('loc-ckr-mch', 'site-ckr', 'loc-ckr-prd', 'area', 'MCH', 'Machining'),
  loc('loc-ckr-cnc', 'site-ckr', 'loc-ckr-mch', 'line', 'CNC', 'CNC Line'),
  loc('loc-ckr-asm', 'site-ckr', 'loc-ckr-prd', 'area', 'ASM', 'Assembly'),
  loc('loc-ckr-as1', 'site-ckr', 'loc-ckr-asm', 'line', 'AS1', 'Assembly Line'),
  loc('loc-ckr-utl', 'site-ckr', null, 'plant', 'UTL', 'Utility'),
  loc('loc-ckr-cmp', 'site-ckr', 'loc-ckr-utl', 'area', 'CMP', 'Compressor & Electrical'),
]

export const costCenters: CostCenter[] = [
  { id: 'cc-bdg-mch', siteId: 'site-bdg', code: 'CC-MCH', name: 'Machining' },
  { id: 'cc-bdg-fin', siteId: 'site-bdg', code: 'CC-FIN', name: 'Finishing' },
  { id: 'cc-bdg-asm', siteId: 'site-bdg', code: 'CC-ASM', name: 'Assembly' },
  { id: 'cc-bdg-utl', siteId: 'site-bdg', code: 'CC-UTL', name: 'Utility' },
  { id: 'cc-ckr-prd', siteId: 'site-ckr', code: 'CC-CKR-PRD', name: 'Production Cikarang' },
  { id: 'cc-ckr-utl', siteId: 'site-ckr', code: 'CC-CKR-UTL', name: 'Utility Cikarang' },
]

export const skills: Skill[] = [
  { id: 'skl-mech', name: 'Mechanical' },
  { id: 'skl-elec', name: 'Electrical' },
  { id: 'skl-plc', name: 'PLC' },
  { id: 'skl-weld', name: 'Welding' },
  { id: 'skl-hyd', name: 'Hydraulic' },
  { id: 'skl-pneu', name: 'Pneumatic' },
  { id: 'skl-inst', name: 'Instrumentation' },
  { id: 'skl-refr', name: 'Refrigeration' },
]

export const teams: Team[] = [
  { id: 'team-bdg-mech', siteId: 'site-bdg', name: 'Mechanical', supervisorId: 'per-hendra' },
  { id: 'team-bdg-elec', siteId: 'site-bdg', name: 'Electrical', supervisorId: 'per-yusuf' },
  { id: 'team-bdg-utl', siteId: 'site-bdg', name: 'Utility', supervisorId: 'per-hendra' },
  { id: 'team-bdg-inst', siteId: 'site-bdg', name: 'Instrument', supervisorId: 'per-yusuf' },
  { id: 'team-ckr-mnt', siteId: 'site-ckr', name: 'Maintenance', supervisorId: 'per-irfan' },
]

const COLORS = [
  '#0F766E',
  '#7C3AED',
  '#B45309',
  '#0369A1',
  '#BE185D',
  '#4D7C0F',
  '#9333EA',
  '#C2410C',
  '#1D4ED8',
  '#15803D',
  '#A16207',
  '#DB2777',
  '#0E7490',
  '#6D28D9',
  '#475569',
  '#9F1239',
]
let colorIdx = 0
const nextColor = () => COLORS[colorIdx++ % COLORS.length]!

function person(
  id: string,
  name: string,
  title: string,
  role: Role,
  siteIds: string[],
  technician: TechnicianProfile | null = null,
): Person {
  const handle = name.split(' ')[0]!.toLowerCase()
  return {
    id,
    name,
    title,
    role,
    email: `${handle}@nusapresisi.co.id`,
    phone: `+62 812 ${String(2000 + colorIdx * 137).slice(0, 4)} ${String(4100 + colorIdx * 311).slice(0, 4)}`,
    color: nextColor(),
    siteIds,
    technician,
  }
}

type SkillMap = Partial<Record<'mech' | 'elec' | 'plc' | 'weld' | 'hyd' | 'pneu' | 'inst' | 'refr', SkillLevel>>
function tech(
  teamId: string,
  shift: TechnicianProfile['shift'],
  hourlyCost: number,
  levels: SkillMap,
  authorizations: string[],
  certifications: TechnicianProfile['certifications'] = [],
  availability: TechnicianProfile['availability'] = 'on_shift',
): TechnicianProfile {
  const skillsMap: Record<string, SkillLevel> = {}
  for (const [k, v] of Object.entries(levels)) skillsMap[`skl-${k}`] = v as SkillLevel
  return { teamId, shift, hourlyCost, skills: skillsMap, certifications, authorizations, availability }
}

const cert = (id: string, name: string, issuer: string, issuedAt: string, expiresAt: string | null) => ({
  id,
  name,
  issuer,
  issuedAt: `${issuedAt}T00:00:00+07:00`,
  expiresAt: expiresAt ? `${expiresAt}T00:00:00+07:00` : null,
})

const BDG = ['site-bdg']
const CKR = ['site-ckr']
const BOTH = ['site-bdg', 'site-ckr']

export const people: Person[] = [
  person('per-rina', 'Rina Kartika', 'Maintenance Manager', 'manager', BOTH),
  person('per-dimas', 'Dimas Pratama', 'Maintenance Planner', 'planner', BDG),
  person('per-hendra', 'Hendra Wijaya', 'Supervisor Mechanical & Utility', 'supervisor', BDG),
  person('per-yusuf', 'Yusuf Hidayat', 'Supervisor Electrical & Instrument', 'supervisor', BDG),
  person('per-sari', 'Sari Lestari', 'Spare Part Warehouse', 'warehouse', BOTH),
  person('per-fajar', 'Fajar Nugroho', 'CMMS Administrator', 'admin', BOTH),
  person('per-bambang', 'Bambang Sutrisno', 'Plant Manager', 'viewer', BOTH),
  person('per-asep', 'Asep Sunandar', 'Operator Finishing', 'requester', BDG),
  person('per-dewi', 'Dewi Anggraini', 'QC Inspector', 'requester', BDG),
  person('per-rudi', 'Rudi Hartono', 'Production Leader Machining', 'requester', BDG),
  person(
    'per-budi',
    'Budi Santoso',
    'Senior Mechanical Technician',
    'technician',
    BDG,
    tech(
      'team-bdg-mech',
      'A',
      85_000,
      { mech: 3, elec: 1, plc: 1, weld: 2, hyd: 2, pneu: 2 },
      ['LOTO', 'Work at height', 'Hot work'],
      [
        cert('crt-budi-1', 'K3 Mechanical Technician', 'Kemnaker RI', '2023-02-10', '2027-02-10'),
        cert('crt-budi-2', 'LOTO Authorized Person', 'Internal HSE', '2025-11-03', '2026-11-03'),
      ],
    ),
  ),
  person(
    'per-andi',
    'Andi Saputra',
    'Mechanical Technician',
    'technician',
    BDG,
    tech('team-bdg-mech', 'A', 70_000, { mech: 2, weld: 1, hyd: 1, pneu: 2 }, ['LOTO'], [
      cert('crt-andi-1', 'LOTO Authorized Person', 'Internal HSE', '2025-11-03', '2026-11-03'),
    ]),
  ),
  person(
    'per-rizky',
    'Rizky Ramadhan',
    'Mechanical Technician',
    'technician',
    BDG,
    tech('team-bdg-mech', 'A', 72_000, { mech: 2, hyd: 3, pneu: 1, weld: 1 }, ['LOTO', 'Work at height'], [
      cert('crt-rizky-1', 'Hydraulic Systems Level 2', 'Parker Training', '2024-08-15', null),
    ]),
  ),
  person(
    'per-agus',
    'Agus Setiawan',
    'Mechanical Technician',
    'technician',
    BDG,
    tech('team-bdg-mech', 'B', 60_000, { mech: 1, weld: 3 }, ['Hot work'], [
      cert('crt-agus-1', 'Welder 3G SMAW', 'BNSP', '2022-05-20', '2026-10-20'),
    ]),
  ),
  person(
    'per-joko',
    'Joko Susilo',
    'Mechanical Technician',
    'technician',
    BDG,
    tech('team-bdg-mech', 'C', 82_000, { mech: 3, hyd: 2, refr: 1, pneu: 1 }, ['LOTO', 'Confined space']),
  ),
  person(
    'per-wahyu',
    'Wahyu Firmansyah',
    'Senior Electrical Technician',
    'technician',
    BDG,
    tech('team-bdg-elec', 'A', 88_000, { elec: 3, plc: 3, inst: 2 }, ['LOTO', 'High voltage'], [
      cert('crt-wahyu-1', 'K3 Electrical', 'Kemnaker RI', '2021-10-30', '2026-10-30'),
      cert('crt-wahyu-2', 'Siemens S7 TIA Portal', 'Siemens Indonesia', '2023-03-12', null),
    ]),
  ),
  person(
    'per-eko',
    'Eko Prasetyo',
    'Electrical Technician',
    'technician',
    BDG,
    tech('team-bdg-elec', 'B', 68_000, { elec: 2, plc: 1 }, ['LOTO'], []),
  ),
  person(
    'per-deni',
    'Deni Kurniawan',
    'Electrical Technician',
    'technician',
    BDG,
    tech('team-bdg-elec', 'C', 70_000, { elec: 2, plc: 2, inst: 1 }, ['LOTO', 'High voltage'], [], 'leave'),
  ),
  person(
    'per-taufik',
    'Taufik Rahman',
    'Utility Technician',
    'technician',
    BDG,
    tech('team-bdg-utl', 'N', 75_000, { mech: 2, refr: 3, pneu: 2, elec: 1 }, ['LOTO', 'Confined space'], [
      cert('crt-taufik-1', 'Refrigeration Technician', 'BNSP', '2024-01-22', '2027-01-22'),
    ]),
  ),
  person(
    'per-lina',
    'Lina Marlina',
    'Instrument Technician',
    'technician',
    BDG,
    tech('team-bdg-inst', 'N', 80_000, { inst: 3, elec: 2, plc: 1 }, ['LOTO'], [
      cert('crt-lina-1', 'Metrology & Calibration Level 2', 'KAN', '2024-06-03', '2027-06-03'),
    ]),
  ),
  person('per-irfan', 'Irfan Maulana', 'Maintenance Supervisor', 'supervisor', CKR),
  person(
    'per-galih',
    'Galih Permana',
    'Maintenance Technician',
    'technician',
    CKR,
    tech('team-ckr-mnt', 'A', 68_000, { mech: 2, elec: 1, pneu: 2 }, ['LOTO']),
  ),
  person(
    'per-hadi',
    'Hadi Gunawan',
    'Maintenance Technician',
    'technician',
    CKR,
    tech('team-ckr-mnt', 'A', 70_000, { elec: 2, plc: 2, inst: 1 }, ['LOTO', 'High voltage']),
  ),
  person(
    'per-fikri',
    'Fikri Hakim',
    'Maintenance Technician',
    'technician',
    CKR,
    tech('team-ckr-mnt', 'B', 66_000, { mech: 2, hyd: 2 }, ['LOTO']),
  ),
  person('per-nina', 'Nina Sari', 'Operator Assembly', 'requester', CKR),
]

const date = (d: string) => `${d}T00:00:00+07:00`

export const vendors: Vendor[] = [
  {
    id: 'ven-abc',
    name: 'ABC Compressor Service',
    serviceTypes: ['Compressor overhaul', 'Air system audit'],
    pic: 'Heru Gunadi',
    phone: '+62 22 7301 884',
    email: 'service@abccompressor.co.id',
    contractNo: 'CTR-2026-011',
    contractStart: date('2026-01-01'),
    contractEnd: date('2026-12-31'),
    slaHours: 24,
    hourlyRate: 350_000,
    rating: 3.6,
  },
  {
    id: 'ven-kalibra',
    name: 'PT Kalibrasi Nusantara',
    serviceTypes: ['Calibration (KAN accredited)', 'Metrology'],
    pic: 'Meiliana Putri',
    phone: '+62 21 8990 1210',
    email: 'order@kalibrasinusantara.id',
    contractNo: 'CTR-2026-004',
    contractStart: date('2026-01-01'),
    contractEnd: date('2026-12-31'),
    slaHours: 72,
    hourlyRate: 250_000,
    rating: 4.6,
  },
  {
    id: 'ven-elektrindo',
    name: 'CV Elektrindo Teknik',
    serviceTypes: ['Panel service', 'Thermography', 'Motor rewinding'],
    pic: 'Anton Siregar',
    phone: '+62 22 6012 447',
    email: 'cs@elektrindo.co.id',
    contractNo: 'CTR-2025-031',
    contractStart: date('2025-07-01'),
    contractEnd: date('2026-06-30'),
    slaHours: 8,
    hourlyRate: 300_000,
    rating: 4.2,
  },
  {
    id: 'ven-hidrolik',
    name: 'PT Hidrolik Jaya',
    serviceTypes: ['Hydraulic repair', 'Cylinder reseal'],
    pic: 'Samuel Tan',
    phone: '+62 21 5530 772',
    email: 'workshop@hidrolikjaya.com',
    contractNo: 'CTR-2026-017',
    contractStart: date('2026-02-01'),
    contractEnd: date('2027-01-31'),
    slaHours: 48,
    hourlyRate: 325_000,
    rating: 4.0,
  },
  {
    id: 'ven-oventech',
    name: 'Oven Tech Indonesia',
    serviceTypes: ['Burner service', 'Combustion tuning'],
    pic: 'Dedi Kusnadi',
    phone: '+62 22 8763 010',
    email: 'support@oventech.id',
    contractNo: 'CTR-2026-009',
    contractStart: date('2026-01-15'),
    contractEnd: date('2027-01-14'),
    slaHours: 24,
    hourlyRate: 400_000,
    rating: 3.4,
  },
  {
    id: 'ven-xyz',
    name: 'XYZ Machinery Indonesia',
    serviceTypes: ['OEM service', 'Warranty claims'],
    pic: 'Kevin Wirawan',
    phone: '+62 21 2957 3300',
    email: 'service.id@xyzmachinery.com',
    contractNo: 'WTY-POL-2024',
    contractStart: date('2024-06-12'),
    contractEnd: date('2027-06-12'),
    slaHours: 48,
    hourlyRate: 450_000,
    rating: 4.1,
  },
  {
    id: 'ven-chillerpro',
    name: 'ChillerPro Service',
    serviceTypes: ['Chiller service', 'Cooling tower'],
    pic: 'Ricky Halim',
    phone: '+62 21 4585 9100',
    email: 'ops@chillerpro.co.id',
    contractNo: 'CTR-2026-020',
    contractStart: date('2026-03-01'),
    contractEnd: date('2027-02-28'),
    slaHours: 12,
    hourlyRate: 375_000,
    rating: 4.4,
  },
  {
    id: 'ven-mitra',
    name: 'Mitra Bearindo',
    serviceTypes: ['Bearings', 'Power transmission'],
    pic: 'Lisa Hartati',
    phone: '+62 22 4231 559',
    email: 'sales@mitrabearindo.com',
    contractNo: 'PO-FRAME-2026-02',
    contractStart: date('2026-01-01'),
    contractEnd: date('2026-12-31'),
    slaHours: 72,
    hourlyRate: 0,
    rating: 4.5,
  },
  {
    id: 'ven-sumber',
    name: 'Sumber Teknik Supplies',
    serviceTypes: ['MRO supplies', 'Electrical parts'],
    pic: 'Yohanes Setiadi',
    phone: '+62 22 6035 118',
    email: 'order@sumberteknik.co.id',
    contractNo: 'PO-FRAME-2026-05',
    contractStart: date('2026-01-01'),
    contractEnd: date('2026-12-31'),
    slaHours: 48,
    hourlyRate: 0,
    rating: 3.9,
  },
]

export const assetTypes: AssetType[] = [
  { id: 'at-polisher', name: 'Polishing Machine', category: 'production', icon: 'polisher' },
  { id: 'at-lathe', name: 'CNC Lathe', category: 'production', icon: 'lathe' },
  { id: 'at-vmc', name: 'CNC Machining Center', category: 'production', icon: 'mill' },
  { id: 'at-press', name: 'Hydraulic Press', category: 'production', icon: 'press' },
  { id: 'at-molding', name: 'Injection Molding Machine', category: 'production', icon: 'molding' },
  { id: 'at-oven', name: 'Curing Oven', category: 'production', icon: 'oven' },
  { id: 'at-booth', name: 'Spray Booth', category: 'production', icon: 'booth' },
  { id: 'at-conveyor', name: 'Conveyor', category: 'production', icon: 'conveyor' },
  { id: 'at-robot', name: 'Screwing Robot', category: 'production', icon: 'robot' },
  { id: 'at-tester', name: 'Leak Tester', category: 'production', icon: 'tester' },
  { id: 'at-packer', name: 'Strapping Machine', category: 'production', icon: 'packer' },
  { id: 'at-forklift', name: 'Forklift', category: 'facility', icon: 'forklift' },
  { id: 'at-compressor', name: 'Air Compressor', category: 'utility', icon: 'compressor' },
  { id: 'at-dryer', name: 'Air Dryer', category: 'utility', icon: 'dryer' },
  { id: 'at-panel', name: 'Electrical Panel', category: 'utility', icon: 'panel' },
  { id: 'at-genset', name: 'Generator Set', category: 'utility', icon: 'genset' },
  { id: 'at-chiller', name: 'Chiller', category: 'utility', icon: 'chiller' },
  { id: 'at-tower', name: 'Cooling Tower', category: 'utility', icon: 'tower' },
  { id: 'at-pump', name: 'Water Pump', category: 'utility', icon: 'pump' },
  { id: 'at-motor', name: 'Electric Motor', category: 'production', icon: 'motor' },
  { id: 'at-spindle', name: 'Spindle', category: 'production', icon: 'spindle' },
  { id: 'at-inverter', name: 'Inverter (VFD)', category: 'production', icon: 'inverter' },
  { id: 'at-plc', name: 'PLC Module', category: 'production', icon: 'plc' },
  { id: 'at-gauge', name: 'Pressure Gauge', category: 'instrument', icon: 'gauge' },
  { id: 'at-thermo', name: 'Thermometer', category: 'instrument', icon: 'thermometer' },
  { id: 'at-scale', name: 'Digital Scale', category: 'instrument', icon: 'scale' },
  { id: 'at-sensor', name: 'Temperature Sensor', category: 'instrument', icon: 'sensor' },
]

const fc = (kind: FailureCode['kind'], code: string, name: string): FailureCode => ({
  id: `fc-${code.toLowerCase()}`,
  kind,
  code,
  name,
})

export const failureCodes: FailureCode[] = [
  fc('problem', 'PRB-HT', 'High temperature'),
  fc('problem', 'PRB-NS', 'Abnormal noise'),
  fc('problem', 'PRB-VB', 'Vibration'),
  fc('problem', 'PRB-LK', 'Leak'),
  fc('problem', 'PRB-NP', 'No power'),
  fc('problem', 'PRB-SM', 'Slow movement'),
  fc('problem', 'PRB-LP', 'Low pressure'),
  fc('problem', 'PRB-TR', 'Trip or alarm'),
  fc('problem', 'PRB-QD', 'Quality defect'),
  fc('problem', 'PRB-ST', 'Will not start'),
  fc('mode', 'FM-BW', 'Bearing wear'),
  fc('mode', 'FM-MF', 'Motor failure'),
  fc('mode', 'FM-SF', 'Sensor failure'),
  fc('mode', 'FM-LC', 'Loose connection'),
  fc('mode', 'FM-SD', 'Seal damage'),
  fc('mode', 'FM-MA', 'Misalignment'),
  fc('mode', 'FM-BB', 'Belt or chain worn'),
  fc('mode', 'FM-CL', 'Clogged filter'),
  fc('mode', 'FM-BN', 'Burner fault'),
  fc('mode', 'FM-CT', 'Contactor failure'),
  fc('mode', 'FM-HY', 'Hydraulic leak'),
  fc('mode', 'FM-PL', 'PLC I/O fault'),
  fc('mode', 'FM-VF', 'Inverter fault'),
  fc('cause', 'CS-WR', 'Wear'),
  fc('cause', 'CS-CT', 'Contamination'),
  fc('cause', 'CS-OV', 'Overload'),
  fc('cause', 'CS-LB', 'Poor lubrication'),
  fc('cause', 'CS-IE', 'Installation error'),
  fc('cause', 'CS-EF', 'Electrical fault'),
  fc('cause', 'CS-AG', 'Aging'),
  fc('cause', 'CS-OP', 'Operating error'),
  fc('cause', 'CS-VB', 'Vibration and looseness'),
  fc('remedy', 'RM-RP', 'Replace'),
  fc('remedy', 'RM-RR', 'Repair'),
  fc('remedy', 'RM-CL', 'Clean'),
  fc('remedy', 'RM-AL', 'Align'),
  fc('remedy', 'RM-LU', 'Lubricate'),
  fc('remedy', 'RM-CA', 'Calibrate'),
  fc('remedy', 'RM-AD', 'Adjust'),
  fc('remedy', 'RM-TG', 'Tighten'),
  fc('remedy', 'RM-RS', 'Reset'),
]
export const fcId = (code: string) => `fc-${code.toLowerCase()}`

const si = (kind: SafetyItem['kind'], key: string, name: string): SafetyItem => ({
  id: `sf-${key}`,
  kind,
  name,
})

export const safetyItems: SafetyItem[] = [
  si('hazard', 'electrical', 'Electrical'),
  si('hazard', 'rotating', 'Rotating equipment'),
  si('hazard', 'hot', 'Hot surface'),
  si('hazard', 'pressure', 'Pressurised system'),
  si('hazard', 'crushing', 'Crushing'),
  si('hazard', 'arcflash', 'Arc flash'),
  si('hazard', 'fire', 'Fire and gas'),
  si('hazard', 'noise', 'Noise'),
  si('hazard', 'entangle', 'Entanglement'),
  si('hazard', 'height', 'Work at height'),
  si('ppe', 'helmet', 'Helmet'),
  si('ppe', 'gloves', 'Gloves'),
  si('ppe', 'glasses', 'Safety glasses'),
  si('ppe', 'shoes', 'Safety shoes'),
  si('ppe', 'egloves', 'Electrical gloves'),
  si('ppe', 'faceshield', 'Arc-flash face shield'),
  si('ppe', 'heatgloves', 'Heat-resistant gloves'),
  si('ppe', 'ear', 'Ear protection'),
  si('ppe', 'harness', 'Safety harness'),
]
export const sf = (key: string) => `sf-${key}`

export const warehouses: Warehouse[] = [
  { id: 'wh-bdg-a', siteId: 'site-bdg', code: 'WH-A', name: 'Warehouse A' },
  { id: 'wh-ckr-c1', siteId: 'site-ckr', code: 'WH-C1', name: 'Warehouse C1' },
]

type PartRow = [
  code: string,
  name: string,
  category: Part['category'],
  unit: string,
  unitCost: number,
  min: number,
  max: number,
  reorderQty: number,
  leadTimeDays: number,
  vendorId: string,
  manufacturer: string,
  spec: string,
  critical?: boolean,
]

const PART_ROWS: PartRow[] = [
  ['BRG-6204', 'Bearing 6204-2RS', 'bearing', 'pcs', 125_000, 4, 15, 8, 7, 'ven-mitra', 'SKF', '20 × 47 × 14 mm, sealed'],
  ['BRG-6205', 'Bearing 6205-2RS', 'bearing', 'pcs', 145_000, 4, 12, 6, 7, 'ven-mitra', 'SKF', '25 × 52 × 15 mm, sealed'],
  ['BRG-6308', 'Bearing 6308-ZZ', 'bearing', 'pcs', 385_000, 2, 6, 4, 14, 'ven-mitra', 'NSK', '40 × 90 × 23 mm, shielded'],
  ['BRG-7014', 'Spindle Bearing 7014 Pair', 'bearing', 'set', 4_850_000, 1, 3, 1, 30, 'ven-xyz', 'NSK', 'Angular contact, matched pair', true],
  ['SEL-ABC', 'Oil Seal ABC 35 × 52 × 7', 'seal', 'pcs', 45_000, 5, 20, 10, 7, 'ven-sumber', 'NOK', 'NBR, double lip'],
  ['SEL-HYD-200', 'Main Cylinder Seal Kit 200 t', 'hydraulic', 'set', 6_750_000, 1, 2, 1, 21, 'ven-hidrolik', 'Parker', 'Piston and rod seals, wipers', true],
  ['CPL-XYZ', 'Jaw Coupling L-100', 'mechanical', 'pcs', 650_000, 1, 4, 2, 14, 'ven-mitra', 'Lovejoy', 'Bore 28 mm, spider 92A'],
  ['BLT-B52', 'V-Belt B-52', 'belt', 'pcs', 95_000, 4, 12, 6, 5, 'ven-sumber', 'Mitsuboshi', 'Classic B section, 52 in'],
  ['BLT-A40', 'V-Belt A-40', 'belt', 'pcs', 65_000, 4, 12, 6, 5, 'ven-sumber', 'Bando', 'Classic A section, 40 in'],
  ['CHN-RS60', 'Roller Chain RS60, 10 ft', 'belt', 'roll', 1_250_000, 1, 4, 2, 14, 'ven-mitra', 'Tsubaki', 'Single strand, pitch 19.05 mm'],
  ['FLT-AIR-37', 'Air Filter Element GA37', 'filter', 'pcs', 1_150_000, 2, 6, 3, 14, 'ven-abc', 'Atlas Copco', '1613 7407 00'],
  ['FLT-OIL-37', 'Oil Filter GA37', 'filter', 'pcs', 680_000, 2, 6, 3, 14, 'ven-abc', 'Atlas Copco', '1613 6105 00'],
  ['SEP-37', 'Oil Separator Element GA37', 'filter', 'pcs', 3_950_000, 1, 2, 1, 21, 'ven-abc', 'Atlas Copco', '2911 0075 00'],
  ['OIL-RS-20', 'Roto-Inject Fluid 20 L', 'lubricant', 'pail', 3_200_000, 1, 4, 2, 14, 'ven-abc', 'Atlas Copco', 'Mineral, 4,000 h'],
  ['GRS-EP2', 'Grease EP2', 'lubricant', 'kg', 85_000, 5, 30, 15, 5, 'ven-sumber', 'Shell Gadus S2', 'Lithium complex, NLGI 2'],
  ['OIL-HYD-46', 'Hydraulic Oil ISO VG 46', 'lubricant', 'L', 38_000, 100, 600, 209, 7, 'ven-sumber', 'Shell Tellus S2 MX', 'Anti-wear, drum 209 L'],
  ['CTR-32A', 'Contactor 32 A, 220 V coil', 'electrical', 'pcs', 875_000, 2, 6, 3, 7, 'ven-sumber', 'Schneider', 'LC1D32M7'],
  ['OLR-32A', 'Thermal Overload Relay 23-32 A', 'electrical', 'pcs', 690_000, 1, 4, 2, 7, 'ven-sumber', 'Schneider', 'LRD32'],
  ['FUS-10A', 'Fuse 10 A gG', 'electrical', 'pcs', 18_000, 10, 50, 20, 3, 'ven-sumber', 'ABB', '10 × 38 mm'],
  ['FAN-INV', 'Inverter Cooling Fan 92 mm', 'electrical', 'pcs', 420_000, 1, 4, 2, 14, 'ven-sumber', 'Yaskawa', '24 V DC, GA500 frame 4'],
  ['PRX-M18', 'Proximity Sensor M18 PNP', 'sensor', 'pcs', 560_000, 2, 6, 3, 10, 'ven-sumber', 'Omron', 'E2E-X8MD1, 8 mm'],
  ['TCK-K', 'Thermocouple Type K, 300 mm', 'sensor', 'pcs', 740_000, 2, 6, 3, 10, 'ven-oventech', 'Omega', 'Grounded junction, 6 mm sheath'],
  ['SOL-52', 'Solenoid Valve 5/2, 24 V DC', 'pneumatic', 'pcs', 890_000, 1, 4, 2, 10, 'ven-sumber', 'SMC', 'SY5120-5DZ'],
  ['PNS-KIT', 'Pneumatic Cylinder Seal Kit 63 mm', 'pneumatic', 'set', 320_000, 2, 6, 3, 10, 'ven-sumber', 'SMC', 'CP96 bore 63'],
  ['NZL-BRN', 'Burner Nozzle 2.5 GPH', 'mechanical', 'pcs', 1_350_000, 1, 4, 2, 21, 'ven-oventech', 'Delavan', '60° hollow cone'],
  ['MTR-7K5', 'Electric Motor 7.5 kW 4P', 'electrical', 'pcs', 9_800_000, 0, 1, 1, 30, 'ven-sumber', 'WEG', 'W22 IE3, frame 132M', true],
  ['PLC-DI16', 'PLC Input Module SM1221 DI16', 'electrical', 'pcs', 4_200_000, 0, 2, 1, 30, 'ven-sumber', 'Siemens', '6ES7221-1BH32-0XB0', true],
  ['HOS-HYD', 'Hydraulic Hose 1/2 in × 1 m', 'hydraulic', 'pcs', 275_000, 2, 8, 4, 7, 'ven-hidrolik', 'Parker', '2-wire braid, JIC ends'],
  ['FLT-HYD', 'Hydraulic Return Filter', 'filter', 'pcs', 520_000, 2, 6, 3, 14, 'ven-hidrolik', 'Hydac', '10 µm, 0160 R 010'],
  ['FLT-DRY', 'Chiller Filter Drier', 'filter', 'pcs', 780_000, 1, 3, 2, 14, 'ven-chillerpro', 'Danfoss', 'DML 165'],
]

export const partId = (code: string) => `part-${code.toLowerCase()}`

export const parts: Part[] = PART_ROWS.map(
  ([code, name, category, unit, unitCost, min, max, reorderQty, leadTimeDays, vendorId, manufacturer, spec, critical]) => ({
    id: partId(code),
    code,
    name,
    category,
    unit,
    unitCost,
    min,
    max,
    reorderQty,
    leadTimeDays,
    vendorId,
    manufacturer,
    spec,
    critical: critical ?? false,
  }),
)

/** Current on-hand stock per warehouse; the generator back-fills a transaction history that ends here. */
export const STOCK_TARGET: Record<string, Record<string, number>> = {
  'wh-bdg-a': {
    'BRG-6204': 3,
    'BRG-6205': 7,
    'BRG-6308': 4,
    'BRG-7014': 2,
    'SEL-ABC': 12,
    'SEL-HYD-200': 1,
    'CPL-XYZ': 2,
    'BLT-B52': 8,
    'BLT-A40': 6,
    'CHN-RS60': 1,
    'FLT-AIR-37': 3,
    'FLT-OIL-37': 3,
    'SEP-37': 1,
    'OIL-RS-20': 2,
    'GRS-EP2': 14,
    'OIL-HYD-46': 380,
    'CTR-32A': 4,
    'OLR-32A': 2,
    'FUS-10A': 36,
    'FAN-INV': 2,
    'PRX-M18': 3,
    'TCK-K': 0,
    'SOL-52': 2,
    'PNS-KIT': 4,
    'NZL-BRN': 2,
    'MTR-7K5': 1,
    'PLC-DI16': 1,
    'HOS-HYD': 6,
    'FLT-HYD': 3,
    'FLT-DRY': 2,
  },
  'wh-ckr-c1': {
    'BRG-6204': 6,
    'BRG-6205': 5,
    'BRG-7014': 1,
    'CTR-32A': 3,
    'FUS-10A': 20,
    'PRX-M18': 0,
    'GRS-EP2': 8,
    'OIL-HYD-46': 220,
    'HOS-HYD': 4,
    'FLT-HYD': 2,
    'CHN-RS60': 1,
    'BLT-A40': 5,
  },
}

const ALL_CHANNELS = (inApp: boolean, email: boolean, whatsapp: boolean, push: boolean): Record<NotificationChannel, boolean> => ({
  in_app: inApp,
  email,
  whatsapp,
  push,
})

const rule = (event: NotificationEvent, channels: Record<NotificationChannel, boolean>, roles: Role[]): NotificationRule => ({
  event,
  channels,
  roles,
})

export const settings: Settings = {
  slaHours: { P1: 4, P2: 24, P3: 72, P4: 168 },
  approvalByPriority: { P1: 'auto', P2: 'supervisor', P3: 'auto', P4: 'auto' },
  managerApprovalAbove: 10_000_000,
  verifyCriticalities: ['A'],
  repeatWindowDays: 30,
  wrenchTime: 0.3,
  weeklyHours: 40,
  notificationRules: [
    rule('pm_due_tomorrow', ALL_CHANNELS(true, false, false, true), ['planner', 'technician']),
    rule('pm_overdue', ALL_CHANNELS(true, true, false, false), ['planner', 'supervisor', 'manager']),
    rule('critical_wo_created', ALL_CHANNELS(true, false, true, true), ['supervisor', 'manager', 'technician']),
    rule('wo_sla_exceeded', ALL_CHANNELS(true, true, true, false), ['supervisor', 'manager']),
    rule('part_below_min', ALL_CHANNELS(true, true, false, false), ['warehouse', 'planner']),
    rule('calibration_expiring', ALL_CHANNELS(true, true, false, false), ['planner', 'supervisor']),
    rule('warranty_expiring', ALL_CHANNELS(true, true, false, false), ['manager', 'planner']),
    rule('repeat_failure', ALL_CHANNELS(true, true, false, false), ['supervisor', 'manager']),
    rule('approval_required', ALL_CHANNELS(true, true, false, true), ['supervisor', 'manager']),
  ],
}
