import type { ChecklistItem, JobPlan, PmSchedule, PmTrigger, SafetyRequirement } from '../../packages/types/src/index.ts'
import { assetId, meterId } from './assets.ts'
import { partId, safetyDetail, sf } from './master.ts'

type Task = Omit<ChecklistItem, 'id'>
const check = (label: string, required = true): Task => ({ label, type: 'check', required })
const passfail = (label: string, required = true, help?: string): Task => ({ label, type: 'passfail', required, help })
const choice = (label: string, options: string[], required = true): Task => ({ label, type: 'choice', required, options })
const photo = (label: string, required = false): Task => ({ label, type: 'photo', required })
const signature = (label = 'Technician sign-off'): Task => ({ label, type: 'signature', required: true })
const text = (label: string, required = true): Task => ({ label, type: 'text', required })
const num = (label: string, unit: string, required = true): Task => ({ label, type: 'number', unit, required })
const meas = (
  label: string,
  unit: string,
  limits: { min?: number; max?: number; warnMin?: number; warnMax?: number },
  required = true,
): Task => ({
  label,
  type: 'measurement',
  unit,
  required,
  min: limits.min ?? null,
  max: limits.max ?? null,
  warnMin: limits.warnMin ?? null,
  warnMax: limits.warnMax ?? null,
})

const safety = (loto: boolean, hazards: string[], ppe: string[], notes = ''): SafetyRequirement => ({
  loto,
  ...safetyDetail(loto, hazards.map(sf)),
  hazardIds: hazards.map(sf),
  ppeIds: ppe.map(sf),
  notes,
})

type PlanDef = Omit<JobPlan, 'id' | 'tasks' | 'parts' | 'updatedAt' | 'active'> & {
  tasks: Task[]
  parts: [string, number][]
  updated: string
}

const DEFS: PlanDef[] = [
  {
    code: 'JP-POL-001',
    name: 'Motor Inspection',
    description: 'Weekly condition check of the polishing drive motor and spindle while the machine runs at normal load.',
    woType: 'inspection',
    assetTypeIds: ['at-polisher'],
    durationMin: 30,
    skillId: 'skl-mech',
    skillLevel: 2,
    personnel: 1,
    toolCategories: ['Thermal gun', 'Vibration meter', 'Multimeter'],
    parts: [],
    safety: safety(false, ['rotating', 'hot'], ['glasses', 'gloves', 'shoes'], 'Keep guards closed. Measure with the machine running.'),
    tasks: [
      passfail('Inspect motor housing for cracks, oil and dust'),
      meas('Motor temperature', '°C', { max: 75, warnMax: 70 }),
      meas('Vibration velocity at drive end', 'mm/s', { max: 7.1, warnMax: 4.5 }),
      choice('Bearing noise', ['Normal', 'Rough', 'Loud']),
      passfail('Coupling and guard condition'),
      photo('Photo of anything abnormal'),
    ],
    acceptance: 'Temperature below 75 °C, vibration below 4.5 mm/s, no abnormal bearing noise.',
    sop: 'SOP-MNT-014 Motor condition check',
    revision: 3,
    updated: '2026-09-08',
  },
  {
    code: 'JP-POL-002',
    name: 'Polishing Machine Monthly PM',
    description: 'Lubrication, belt, runout and safety checks on polishing machines.',
    woType: 'preventive',
    assetTypeIds: ['at-polisher'],
    durationMin: 90,
    skillId: 'skl-mech',
    skillLevel: 2,
    personnel: 1,
    toolCategories: ['Grease gun', 'Torque wrench', 'Dial gauge'],
    parts: [['GRS-EP2', 1]],
    safety: safety(true, ['rotating', 'electrical'], ['glasses', 'gloves', 'shoes']),
    tasks: [
      check('Lock out main isolator and verify zero energy'),
      check('Grease spindle and motor bearings'),
      meas('V-belt deflection', 'mm', { min: 8, max: 14, warnMin: 9, warnMax: 12 }),
      check('Clean dust extraction filter'),
      check('Tighten terminals in the control box'),
      meas('Spindle runout', 'mm', { max: 0.05, warnMax: 0.03 }),
      passfail('Emergency stop test'),
      signature(),
    ],
    acceptance: 'Runout within 0.03 mm and the E-stop halts the spindle within 2 s.',
    sop: 'SOP-MNT-015 Polishing machine PM',
    revision: 5,
    updated: '2026-02-11',
  },
  {
    code: 'JP-POL-003',
    name: 'Motor Bearing Replacement',
    description: 'Standard job for replacing the 6204 drive bearings and oil seal on polishing machines.',
    woType: 'corrective',
    assetTypeIds: ['at-polisher', 'at-motor', 'at-spindle'],
    durationMin: 120,
    skillId: 'skl-mech',
    skillLevel: 2,
    personnel: 2,
    toolCategories: ['Bearing puller', 'Torque wrench', 'Vibration meter'],
    parts: [
      ['BRG-6204', 2],
      ['SEL-ABC', 1],
    ],
    safety: safety(true, ['rotating', 'crushing'], ['glasses', 'gloves', 'shoes']),
    tasks: [
      check('Lock out and tag the main isolator'),
      check('Remove belt guard and drive belt'),
      check('Pull both bearings with the bearing puller'),
      passfail('Shaft and housing condition'),
      check('Fit new bearings and oil seal'),
      meas('Housing bolt torque', 'N·m', { min: 45, max: 55 }),
      meas('Run test vibration', 'mm/s', { max: 4.5, warnMax: 2.8 }),
      photo('Photo after repair'),
    ],
    acceptance: 'Vibration below 2.8 mm/s after a 15 minute run.',
    sop: 'SOP-MNT-016 Bearing replacement',
    revision: 2,
    updated: '2025-12-04',
  },
  {
    code: 'JP-CMP-001',
    name: 'Compressor 500 h Check',
    description: 'Running-hour based check on screw compressors.',
    woType: 'preventive',
    assetTypeIds: ['at-compressor'],
    durationMin: 60,
    skillId: 'skl-mech',
    skillLevel: 1,
    personnel: 1,
    toolCategories: ['Multimeter'],
    parts: [],
    safety: safety(false, ['hot', 'noise', 'pressure'], ['ear', 'glasses', 'gloves']),
    tasks: [
      passfail('Oil level in sight glass'),
      check('Drain condensate and test the auto drain'),
      check('Blow clean the air filter'),
      meas('Discharge pressure', 'bar', { min: 6.5, max: 7.8, warnMin: 6.8 }),
      meas('Element outlet temperature', '°C', { max: 110, warnMax: 100 }),
      passfail('Air and oil leak check'),
      num('Running hours', 'h'),
    ],
    acceptance: 'Pressure at least 6.8 bar and element outlet below 100 °C.',
    sop: 'SOP-UTL-004 Compressor routine check',
    revision: 4,
    updated: '2025-10-20',
  },
  {
    code: 'JP-CMP-002',
    name: 'Compressor 4,000 h Service',
    description: 'Filter, separator and oil change on GA37 compressors. Usually done with ABC Compressor Service.',
    woType: 'preventive',
    assetTypeIds: ['at-compressor'],
    durationMin: 480,
    skillId: 'skl-mech',
    skillLevel: 2,
    personnel: 2,
    toolCategories: ['Torque wrench', 'Multimeter'],
    parts: [
      ['FLT-AIR-37', 1],
      ['FLT-OIL-37', 1],
      ['SEP-37', 1],
      ['OIL-RS-20', 1],
    ],
    safety: safety(true, ['pressure', 'hot', 'electrical'], ['gloves', 'glasses', 'ear']),
    tasks: [
      check('Depressurise and lock out'),
      check('Replace air filter'),
      check('Replace oil filter'),
      check('Replace oil separator'),
      check('Change oil, 18 L'),
      choice('Motor bearing noise', ['Normal', 'Rough', 'Loud']),
      meas('Motor current at full load', 'A', { max: 72, warnMax: 68 }),
      passfail('Leak test after restart'),
      photo('Service report', true),
      signature(),
    ],
    acceptance: 'No leaks after restart and motor current below 68 A.',
    sop: 'SOP-UTL-005 Compressor major service',
    revision: 2,
    updated: '2025-08-14',
  },
  {
    code: 'JP-OVN-001',
    name: 'Oven Burner Service',
    description: 'Monthly burner cleaning, flame check and zone temperature verification.',
    woType: 'preventive',
    assetTypeIds: ['at-oven'],
    durationMin: 120,
    skillId: 'skl-mech',
    skillLevel: 2,
    personnel: 1,
    toolCategories: ['Thermal gun', 'Multimeter'],
    parts: [],
    safety: safety(true, ['hot', 'fire'], ['heatgloves', 'faceshield', 'shoes'], 'Isolate the gas valve and let the oven cool below 50 °C.'),
    tasks: [
      check('Isolate gas and power, cool below 50 °C'),
      check('Clean burner nozzle and ignition electrode'),
      meas('Flame detector signal', 'µA', { min: 2, warnMin: 4 }),
      passfail('Combustion air fan belt condition'),
      meas('Zone temperature at 180 °C setpoint', '°C', { min: 175, max: 185, warnMin: 177, warnMax: 183 }),
      passfail('Door seal condition'),
      meas('Thermocouple deviation from reference', '°C', { max: 5, warnMax: 3 }),
    ],
    acceptance: 'Zone within ±3 °C of setpoint and flame signal above 4 µA.',
    sop: 'SOP-MNT-021 Burner service',
    revision: 3,
    updated: '2025-11-12',
  },
  {
    code: 'JP-CNC-001',
    name: 'CNC Lathe Quarterly PM',
    description: 'Accuracy, lubrication and hydraulic checks on CNC lathes.',
    woType: 'preventive',
    assetTypeIds: ['at-lathe'],
    durationMin: 180,
    skillId: 'skl-mech',
    skillLevel: 2,
    personnel: 1,
    toolCategories: ['Dial gauge', 'Vibration meter', 'Grease gun'],
    parts: [['FLT-HYD', 1]],
    safety: safety(true, ['rotating'], ['glasses', 'gloves', 'shoes']),
    tasks: [
      passfail('Way lube level and flow'),
      meas('Coolant concentration', '%', { min: 5, max: 8 }),
      meas('Chuck hydraulic pressure', 'bar', { min: 15, max: 25 }),
      meas('Backlash X axis', 'mm', { max: 0.01, warnMax: 0.006 }),
      meas('Backlash Z axis', 'mm', { max: 0.01, warnMax: 0.006 }),
      meas('Spindle vibration at 2,000 rpm', 'mm/s', { max: 2.8, warnMax: 1.8 }),
      check('Replace hydraulic return filter'),
      check('Back up machine parameters'),
      signature(),
    ],
    acceptance: 'Backlash within 0.006 mm and spindle vibration below 1.8 mm/s.',
    sop: 'SOP-MNT-030 CNC lathe PM',
    revision: 2,
    updated: '2025-06-02',
  },
  {
    code: 'JP-VMC-001',
    name: 'Machining Center Monthly PM',
    description: 'Spindle, tool changer and lubrication checks on vertical machining centers.',
    woType: 'preventive',
    assetTypeIds: ['at-vmc'],
    durationMin: 120,
    skillId: 'skl-mech',
    skillLevel: 2,
    personnel: 1,
    toolCategories: ['Dial gauge', 'Vibration meter'],
    parts: [],
    safety: safety(true, ['rotating'], ['glasses', 'gloves', 'shoes']),
    tasks: [
      meas('Spindle vibration', 'mm/s', { max: 2.8, warnMax: 1.8 }),
      passfail('Tool changer cycle test'),
      passfail('Way lube level'),
      meas('Coolant concentration', '%', { min: 5, max: 8 }),
      meas('Air pressure at regulator', 'bar', { min: 5.5, max: 7 }),
      check('Clean chip conveyor'),
      check('Back up parameters and macros'),
    ],
    acceptance: 'Spindle vibration below 1.8 mm/s and a clean tool change cycle.',
    sop: 'SOP-MNT-031 Machining center PM',
    revision: 1,
    updated: '2025-09-18',
  },
  {
    code: 'JP-HPR-001',
    name: 'Hydraulic Press Monthly PM',
    description: 'Hydraulic condition and guarding checks on presses.',
    woType: 'preventive',
    assetTypeIds: ['at-press'],
    durationMin: 90,
    skillId: 'skl-hyd',
    skillLevel: 2,
    personnel: 1,
    toolCategories: ['Thermal gun'],
    parts: [],
    safety: safety(true, ['crushing', 'pressure', 'electrical'], ['glasses', 'gloves', 'shoes']),
    tasks: [
      passfail('Hydraulic oil level'),
      meas('Oil temperature after 30 minutes', '°C', { max: 60, warnMax: 55 }),
      meas('System pressure at full tonnage', 'bar', { min: 190, max: 210 }),
      passfail('Hoses and fittings free of leaks'),
      passfail('Two-hand control and light curtain test', true, 'Stop work and tag out the press if either test fails.'),
      photo('Photo of the oil sight glass'),
    ],
    acceptance: 'No leaks, oil below 55 °C, both safety devices stop the ram.',
    sop: 'SOP-SAF-003 Light curtain test',
    revision: 4,
    updated: '2026-03-20',
  },
  {
    code: 'JP-INJ-001',
    name: 'Injection Molding 50,000 Shot PM',
    description: 'Shot-count based PM on injection molding machines.',
    woType: 'preventive',
    assetTypeIds: ['at-molding'],
    durationMin: 120,
    skillId: 'skl-hyd',
    skillLevel: 2,
    personnel: 1,
    toolCategories: ['Grease gun', 'Clamp meter'],
    parts: [['GRS-EP2', 1]],
    safety: safety(true, ['crushing', 'hot', 'electrical'], ['heatgloves', 'glasses', 'shoes']),
    tasks: [
      check('Lubricate toggle links'),
      meas('Heater band current, zone 1 to 5', 'A', { min: 7, max: 10 }),
      meas('Hydraulic oil temperature', '°C', { max: 55, warnMax: 50 }),
      meas('Platen parallelism', 'mm', { max: 0.1, warnMax: 0.06 }),
      passfail('Nozzle free of leaks'),
      passfail('Safety gate interlock test'),
    ],
    acceptance: 'All heater zones within range and the gate interlock stops the clamp.',
    sop: 'SOP-MNT-040 Molding machine PM',
    revision: 2,
    updated: '2025-12-15',
  },
  {
    code: 'JP-PNL-001',
    name: 'Panel Thermography and Tightening',
    description: 'Quarterly thermal scan under load, then tightening and insulation test during a shutdown window.',
    woType: 'preventive',
    assetTypeIds: ['at-panel'],
    durationMin: 150,
    skillId: 'skl-elec',
    skillLevel: 2,
    personnel: 2,
    toolCategories: ['Thermal camera', 'Insulation tester', 'Torque wrench'],
    parts: [],
    safety: safety(true, ['electrical', 'arcflash'], ['egloves', 'faceshield', 'shoes'], 'Scan with doors open under load from outside the arc-flash boundary.'),
    tasks: [
      meas('Hottest joint rise over similar phase (ΔT)', '°C', { max: 15, warnMax: 4 }),
      photo('Thermogram of the hottest point', true),
      check('Tighten busbar and breaker terminals'),
      meas('Insulation resistance phase to earth', 'MΩ', { min: 1, warnMin: 100 }),
      passfail('Panel fans and filters clean'),
      signature(),
    ],
    acceptance: 'No joint above 4 °C ΔT and insulation above 100 MΩ.',
    sop: 'SOP-ELE-007 Panel thermography',
    revision: 3,
    updated: '2026-01-09',
  },
  {
    code: 'JP-CNV-001',
    name: 'Conveyor Weekly Inspection',
    description: 'Walk-down inspection of chain, gearbox and emergency stops.',
    woType: 'inspection',
    assetTypeIds: ['at-conveyor'],
    durationMin: 20,
    skillId: 'skl-mech',
    skillLevel: 1,
    personnel: 1,
    toolCategories: ['Thermal gun'],
    parts: [],
    safety: safety(false, ['entangle'], ['glasses', 'gloves']),
    tasks: [
      passfail('Chain tension and wear'),
      check('Lubricate chain'),
      choice('Gearbox noise', ['Normal', 'Rough', 'Loud']),
      meas('Drive motor temperature', '°C', { max: 80, warnMax: 70 }),
      passfail('Emergency pull-cord test'),
    ],
    acceptance: 'Pull-cord stops the line and gearbox noise is normal.',
    sop: 'SOP-MNT-050 Conveyor walk-down',
    revision: 1,
    updated: '2026-07-01',
  },
  {
    code: 'JP-CHL-001',
    name: 'Chiller Monthly PM',
    description: 'Refrigerant circuit readings and condenser cleaning.',
    woType: 'preventive',
    assetTypeIds: ['at-chiller'],
    durationMin: 90,
    skillId: 'skl-refr',
    skillLevel: 2,
    personnel: 1,
    toolCategories: ['Clamp meter', 'Thermal gun'],
    parts: [],
    safety: safety(false, ['electrical', 'pressure'], ['gloves', 'glasses']),
    tasks: [
      meas('Suction pressure', 'psi', { min: 45, max: 75, warnMin: 50, warnMax: 70 }),
      meas('Discharge pressure', 'psi', { min: 150, max: 260, warnMax: 240 }),
      meas('Leaving chilled water temperature', '°C', { min: 5, max: 10, warnMax: 8 }),
      meas('Compressor current', 'A', { max: 48, warnMax: 44 }),
      check('Clean condenser coil'),
      signature(),
    ],
    acceptance: 'Leaving water below 8 °C with compressor current below 44 A.',
    sop: 'SOP-UTL-012 Chiller PM',
    revision: 2,
    updated: '2026-03-02',
  },
  {
    code: 'JP-GEN-001',
    name: 'Genset Weekly Run Test',
    description: 'No-load run test to keep the standby genset ready.',
    woType: 'inspection',
    assetTypeIds: ['at-genset'],
    durationMin: 30,
    skillId: 'skl-elec',
    skillLevel: 1,
    personnel: 1,
    toolCategories: ['Multimeter'],
    parts: [],
    safety: safety(false, ['noise', 'electrical', 'hot'], ['ear', 'gloves']),
    tasks: [
      passfail('Coolant level'),
      meas('Battery voltage', 'V', { min: 24, warnMin: 25 }),
      check('Run 15 minutes at no load'),
      meas('Oil pressure at idle', 'bar', { min: 2, warnMin: 2.5 }),
      num('Fuel level', '%'),
      num('Hour meter reading', 'h'),
    ],
    acceptance: 'Starts on first attempt and battery above 25 V.',
    sop: 'SOP-ELE-011 Genset test',
    revision: 1,
    updated: '2025-10-01',
  },
  {
    code: 'JP-CAL-001',
    name: 'Instrument Calibration',
    description: 'As-found and as-left calibration against a traceable reference, usually through PT Kalibrasi Nusantara.',
    woType: 'calibration',
    assetTypeIds: ['at-gauge', 'at-thermo', 'at-scale', 'at-sensor'],
    durationMin: 60,
    skillId: 'skl-inst',
    skillLevel: 2,
    personnel: 1,
    toolCategories: ['Multimeter'],
    parts: [],
    safety: safety(false, [], ['glasses']),
    tasks: [
      meas('As-found error', '%', { max: 1.6, warnMax: 1 }),
      check('Adjust if outside tolerance', false),
      meas('As-left error', '%', { max: 1, warnMax: 0.6 }),
      text('Certificate number'),
      photo('Photo of calibration label'),
    ],
    acceptance: 'As-left error within 0.6 % of span.',
    sop: 'SOP-INS-002 Calibration handling',
    revision: 2,
    updated: '2025-07-15',
  },
  {
    code: 'JP-FLT-001',
    name: 'Forklift 250 h Service',
    description: 'Hour-meter based service on diesel forklifts.',
    woType: 'preventive',
    assetTypeIds: ['at-forklift'],
    durationMin: 90,
    skillId: 'skl-mech',
    skillLevel: 1,
    personnel: 1,
    toolCategories: ['Grease gun'],
    parts: [['GRS-EP2', 1]],
    safety: safety(false, ['crushing'], ['gloves', 'shoes']),
    tasks: [
      passfail('Engine oil level'),
      passfail('Hydraulic oil level'),
      check('Lubricate mast chains'),
      passfail('Brake test'),
      passfail('Horn and lights'),
      choice('Tyre condition', ['Good', 'Worn', 'Replace']),
      num('Hour meter reading', 'h'),
    ],
    acceptance: 'Brakes hold on the ramp with rated load.',
    sop: 'SOP-MNT-060 Forklift service',
    revision: 1,
    updated: '2025-05-06',
  },
]

export const jobPlanId = (code: string) => `jp-${code.toLowerCase()}`

export const jobPlans: JobPlan[] = DEFS.map(({ tasks, parts, updated, ...rest }) => ({
  ...rest,
  id: jobPlanId(rest.code),
  tasks: tasks.map((t, i) => ({
    ...(Object.fromEntries(Object.entries(t).filter(([, v]) => v !== null && v !== undefined)) as Task),
    id: `t${i + 1}`,
  })),
  parts: parts.map(([code, qty]) => ({ partId: partId(code), qty })),
  updatedAt: `${updated}T10:00:00+07:00`,
  active: true,
}))

export const JP = (code: string): JobPlan => {
  const plan = jobPlans.find((p) => p.code === code)
  if (!plan) throw new Error(`Unknown job plan ${code}`)
  return plan
}

// ─── PM schedules ───────────────────────────────────────────────

type PmDef = {
  code: string
  name: string
  asset: string
  plan: string
  trigger: PmTrigger
  lastDone: string
  lastMeter?: number
  lead: number
  team: string
  assignee?: string
  /** First occurrence kept in history. Weekly routes started in July. */
  historyFrom?: string
}

const cal = (every: number, unit: 'day' | 'week' | 'month' | 'year'): PmTrigger => ({ kind: 'calendar', every, unit })
const meter = (asset: string, kind: 'runtime' | 'cycle', every: number): PmTrigger => ({
  kind: 'meter',
  meterId: meterId(asset, kind),
  every,
})

export const PM_DEFS: PmDef[] = [
  { code: 'PM-0001', name: 'Poles 01 monthly PM', asset: 'POL-01', plan: 'JP-POL-002', trigger: cal(1, 'month'), lastDone: '2026-08-22', lead: 3, team: 'team-bdg-mech', assignee: 'per-budi' },
  { code: 'PM-0002', name: 'Poles 02 monthly PM', asset: 'POL-02', plan: 'JP-POL-002', trigger: cal(1, 'month'), lastDone: '2026-09-03', lead: 3, team: 'team-bdg-mech', assignee: 'per-andi' },
  {
    code: 'PM-0003',
    name: 'Poles 03 monthly PM',
    asset: 'POL-03',
    plan: 'JP-POL-002',
    trigger: { kind: 'combined', every: 30, unit: 'day', meterId: meterId('POL-03', 'runtime'), meterEvery: 500 },
    lastDone: '2026-09-10',
    lastMeter: 8_230,
    lead: 3,
    team: 'team-bdg-mech',
    assignee: 'per-budi',
  },
  { code: 'PM-0004', name: 'Poles 01 weekly motor inspection', asset: 'POL-01', plan: 'JP-POL-001', trigger: cal(1, 'week'), lastDone: '2026-09-21', lead: 1, team: 'team-bdg-mech', assignee: 'per-andi', historyFrom: '2026-07-13' },
  { code: 'PM-0005', name: 'Poles 02 weekly motor inspection', asset: 'POL-02', plan: 'JP-POL-001', trigger: cal(1, 'week'), lastDone: '2026-09-15', lead: 1, team: 'team-bdg-mech', assignee: 'per-budi', historyFrom: '2026-07-14' },
  { code: 'PM-0006', name: 'Poles 03 weekly motor inspection', asset: 'POL-03', plan: 'JP-POL-001', trigger: cal(1, 'week'), lastDone: '2026-09-21', lead: 1, team: 'team-bdg-mech', assignee: 'per-andi', historyFrom: '2026-07-13' },
  { code: 'PM-0007', name: 'Oven 1 burner service', asset: 'OVN-01', plan: 'JP-OVN-001', trigger: cal(1, 'month'), lastDone: '2026-08-24', lead: 3, team: 'team-bdg-mech', assignee: 'per-rizky' },
  { code: 'PM-0008', name: 'Oven 2 burner service', asset: 'OVN-02', plan: 'JP-OVN-001', trigger: cal(1, 'month'), lastDone: '2026-09-08', lead: 3, team: 'team-bdg-mech', assignee: 'per-rizky' },
  { code: 'PM-0009', name: 'CNC Lathe 01 quarterly PM', asset: 'CNC-01', plan: 'JP-CNC-001', trigger: cal(3, 'month'), lastDone: '2026-06-22', lead: 5, team: 'team-bdg-mech', assignee: 'per-rizky' },
  { code: 'PM-0010', name: 'CNC Lathe 02 quarterly PM', asset: 'CNC-02', plan: 'JP-CNC-001', trigger: cal(3, 'month'), lastDone: '2026-07-15', lead: 5, team: 'team-bdg-mech', assignee: 'per-rizky' },
  { code: 'PM-0011', name: 'Machining Center 01 monthly PM', asset: 'VMC-01', plan: 'JP-VMC-001', trigger: cal(1, 'month'), lastDone: '2026-09-01', lead: 3, team: 'team-bdg-mech', assignee: 'per-joko' },
  { code: 'PM-0012', name: 'Press 200T monthly PM', asset: 'HPR-01', plan: 'JP-HPR-001', trigger: cal(1, 'month'), lastDone: '2026-09-05', lead: 3, team: 'team-bdg-mech', assignee: 'per-rizky' },
  { code: 'PM-0013', name: 'Press 100T monthly PM', asset: 'HPR-02', plan: 'JP-HPR-001', trigger: cal(1, 'month'), lastDone: '2026-08-19', lead: 3, team: 'team-bdg-mech' },
  { code: 'PM-0014', name: 'Molding 01 every 50,000 shots', asset: 'INJ-01', plan: 'JP-INJ-001', trigger: meter('INJ-01', 'cycle', 50_000), lastDone: '2026-09-03', lastMeter: 1_198_000, lead: 2, team: 'team-bdg-mech', assignee: 'per-joko' },
  { code: 'PM-0015', name: 'Molding 02 every 50,000 shots', asset: 'INJ-02', plan: 'JP-INJ-001', trigger: meter('INJ-02', 'cycle', 50_000), lastDone: '2026-09-15', lastMeter: 1_080_000, lead: 2, team: 'team-bdg-mech', assignee: 'per-joko' },
  { code: 'PM-0016', name: 'Compressor 01 every 500 h', asset: 'CMP-01', plan: 'JP-CMP-001', trigger: meter('CMP-01', 'runtime', 500), lastDone: '2026-09-04', lastMeter: 20_960, lead: 2, team: 'team-bdg-utl', assignee: 'per-taufik' },
  { code: 'PM-0017', name: 'Compressor 01 every 4,000 h', asset: 'CMP-01', plan: 'JP-CMP-002', trigger: meter('CMP-01', 'runtime', 4_000), lastDone: '2026-08-18', lastMeter: 20_690, lead: 14, team: 'team-bdg-utl', assignee: 'per-taufik' },
  { code: 'PM-0018', name: 'Compressor 02 every 500 h', asset: 'CMP-02', plan: 'JP-CMP-001', trigger: meter('CMP-02', 'runtime', 500), lastDone: '2026-06-12', lastMeter: 9_500, lead: 2, team: 'team-bdg-utl', assignee: 'per-taufik' },
  { code: 'PM-0019', name: 'Main panel quarterly thermography', asset: 'PNL-01', plan: 'JP-PNL-001', trigger: cal(3, 'month'), lastDone: '2026-09-19', lead: 7, team: 'team-bdg-elec', assignee: 'per-wahyu' },
  { code: 'PM-0020', name: 'Distribution panel quarterly thermography', asset: 'PNL-02', plan: 'JP-PNL-001', trigger: cal(3, 'month'), lastDone: '2026-06-20', lead: 7, team: 'team-bdg-elec', assignee: 'per-wahyu' },
  { code: 'PM-0021', name: 'Assembly conveyor weekly inspection', asset: 'CNV-01', plan: 'JP-CNV-001', trigger: cal(1, 'week'), lastDone: '2026-09-16', lead: 1, team: 'team-bdg-mech', assignee: 'per-andi', historyFrom: '2026-07-15' },
  { code: 'PM-0022', name: 'Coating conveyor weekly inspection', asset: 'CNV-02', plan: 'JP-CNV-001', trigger: cal(1, 'week'), lastDone: '2026-09-16', lead: 0, team: 'team-bdg-mech', assignee: 'per-andi', historyFrom: '2026-07-15' },
  { code: 'PM-0023', name: 'Chiller 01 monthly PM', asset: 'CHL-01', plan: 'JP-CHL-001', trigger: cal(1, 'month'), lastDone: '2026-08-28', lead: 3, team: 'team-bdg-utl', assignee: 'per-taufik' },
  { code: 'PM-0024', name: 'Genset weekly run test', asset: 'GEN-01', plan: 'JP-GEN-001', trigger: cal(1, 'week'), lastDone: '2026-09-15', lead: 1, team: 'team-bdg-elec', assignee: 'per-eko', historyFrom: '2026-07-14' },
  { code: 'PM-0025', name: 'Forklift every 250 h', asset: 'FLT-01', plan: 'JP-FLT-001', trigger: meter('FLT-01', 'runtime', 250), lastDone: '2026-09-09', lastMeter: 6_250, lead: 2, team: 'team-bdg-mech', assignee: 'per-agus' },
  { code: 'PM-0026', name: 'CK Lathe 01 quarterly PM', asset: 'CKR-CNC-01', plan: 'JP-CNC-001', trigger: cal(3, 'month'), lastDone: '2026-07-06', lead: 5, team: 'team-ckr-mnt', assignee: 'per-galih' },
  { code: 'PM-0027', name: 'CK Press 150T monthly PM', asset: 'CKR-HPR-01', plan: 'JP-HPR-001', trigger: cal(1, 'month'), lastDone: '2026-08-25', lead: 3, team: 'team-ckr-mnt', assignee: 'per-fikri' },
  { code: 'PM-0028', name: 'CK Compressor every 500 h', asset: 'CKR-CMP-01', plan: 'JP-CMP-001', trigger: meter('CKR-CMP-01', 'runtime', 500), lastDone: '2026-09-17', lastMeter: 10_780, lead: 2, team: 'team-ckr-mnt', assignee: 'per-galih' },
  { code: 'PM-0029', name: 'CK Main panel quarterly thermography', asset: 'CKR-PNL-01', plan: 'JP-PNL-001', trigger: cal(3, 'month'), lastDone: '2026-07-20', lead: 7, team: 'team-ckr-mnt', assignee: 'per-hadi' },
]

export const pmId = (code: string) => `pm-${code.toLowerCase()}`

export const pmSchedules: PmSchedule[] = PM_DEFS.map((p) => ({
  id: pmId(p.code),
  code: p.code,
  name: p.name,
  siteId: p.asset.startsWith('CKR') ? 'site-ckr' : 'site-bdg',
  assetId: assetId(p.asset),
  jobPlanId: jobPlanId(p.plan),
  trigger: p.trigger,
  lastDoneAt: `${p.lastDone}T15:00:00+07:00`,
  lastDoneMeter: p.lastMeter ?? null,
  leadDays: p.lead,
  teamId: p.team,
  assigneeId: p.assignee ?? null,
  active: true,
}))
